### ISSUE TITLE
Why not_path field in AccessRule is $hide_in_docs-ed

### ISSUE THREAD

**Issue by zhranklin** [istio/api#1043]
**Describe the feature request**
Exclude some paths in rules of ServiceRole. Maybe this is not a feature request because it has been implemented according to code implementation. I want to know if this feature(not_path field) is stable and why not_path field should be hidden in istio docs?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by zhranklin** [comment]
code:

https://github.com/istio/api/blob/0d1db548cf57ed2184cd0c35888e8b207564903b/rbac/v1alpha1/rbac.proto#L128-L130

**Comment by zhranklin** [comment]
Same issue to EnforcementMode because it's referenced in <https://istio.io/docs/tasks/security/authz-permissive/>. Maybe comment of this type is out of date?

https://github.com/istio/api/blob/0d1db548cf57ed2184cd0c35888e8b207564903b/rbac/v1alpha1/rbac.proto#L173-L178

**Comment by esnible** [comment]
I created https://github.com/istio/istio.io/issues/5071 in the istio.io repo before I saw this item.

I am working on an analyzer for deprecated fields.  I want guidance on what to do about hidden non-deprecated fields.  For hidden fields in Subject such as `not_groups` should the user move that into `properties["not_groups"]`?  For fields in AccessRule such as `not_path` there is no properties field so that can't be the answer.

**Comment by pitlv2109** [comment]
Stuff that has $hide_in_docs is under development/experimentation mode and not ready to use.

**Comment by esnible** [comment]
> Stuff that has $hide_in_docs is under development/experimentation mode and not ready to use.

Can we add "introduced in Istio 1.x but not ready to use" to the hidden text for experimental features?

The problem is that I, as a developer, can't tell the difference between fields that are added and awaiting an implementation and fields that have been hidden because we are discouraging them.

**Comment by yangminzhu** [comment]
It's an experimental change to the old (and now deprecated) RBAC API that we never released it to public. Please use the new AuthorizationPolicy that now includes the formal support for `not_paths`.
