### ISSUE TITLE
Configurable StatName in mesh config

### ISSUE THREAD

**Issue by ramaraochavali** [istio/api#1051]
**Describe the feature request**
For all cluster stats that Envoy generates with Istio are of the form 
cluster.inbound|<port>|<port-name>|<service-FQDN> or cluster.outbound|<port>|<port-name>|<service-FQDN> depending on whether the cluster is an inbound or outbound cluster. This is because Istio generates cluster names of the form <traffic-direction>|<port>|<port-name>|<service-FQDN>.

We would the stats to use  a different cluster name rather than the name generated by Istio. Envoy supports that feature by allowing to specify alt_stat_name while defining the cluster https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto.html?highlight=alt_stat_name.

The feature request is to allow this to be specified/configured via `MeshConfig`. Add a new configuration in `MeshConfig` called `stat_name` that when specified uses it to set the `alt_stat_name` of cluster.

**Describe alternatives you've considered**
None

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by mandarjog** [comment]
This is more inline with patching generated config.
Alt_stat_name is destination rule will have to be a pattern so that pilot can substitute it correctly.

**Comment by ramaraochavali** [comment]
@mandarjog 
I am assuming "This is more inline with patching generated config." you meant the new EnvoyFilter way of patching generated config? 

If we specify `stat_name` here, Pilot while generating config for cluster, can set it accordingly. For people who are already using DestintationRules it is much easier to set it like that.  But if we have to set it via patching generated config, we will have create DestinationRule + EnvoyFilter for each cluster ?
So I think it would be useful to have it here as well.

**Comment by ramaraochavali** [comment]
@mandarjog rereading your comment, I think you are OK to have this field here but you want it to be a pattern? Can you give an example of how that pattern should look like? I am planning to push a PR to add this field to DR.

**Comment by ramaraochavali** [comment]
Closed via #1063 https://github.com/istio/api/pull/1063
