### ISSUE TITLE
Approve Cherry Pick PR https://github.com/istio/api/pull/1074

### ISSUE THREAD

**Issue by ramaraochavali** [istio/api#1080]
**Describe the feature request**
Request to allow cherry pick the API change https://github.com/istio/api/pull/1074 to Release 1.3. This is a minor harmless change and would be enabled only on configuration that is enabled only on configuration.

**Describe alternatives you've considered**
N/A
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience

**Additional context**

**Comment by geeknoid** [comment]
We don't need an issue that's just a pointer to a PR.
