### ISSUE TITLE
is there example to use istio api?

### ISSUE THREAD

**Issue by wenweihu86** [istio/api#1174]
**Describe the feature request**
is there example to use istio api?
just like the envoy xds api example:
https://github.com/envoyproxy/java-control-plane

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by hzxuzhonghu** [comment]
@wenweihu86 We donot have api doc yet, but volcano uses the standard CRD. So the best guide to learning how to use the api is from reading the job controller code now.

**Comment by howardjohn** [comment]
istio.io contains API docs. https://github.com/istio/client-go contains client docs
