### ISSUE TITLE
'Deny all' authorization policy example doesn't work

### ISSUE THREAD

**Issue by rolandkool** [istio/api#1183]
**Bug description**
The deny-all example authorization policy as described on this page does not work: https://istio.io/docs/reference/config/security/authorization-policy/

When applying it, the following error is thrown:

> The AuthorizationPolicy "deny-all" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"security.istio.io/v1beta1", "kind":"AuthorizationPolicy", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","metadata":{"annotations":{},"name":"deny-all","namespace":"rkl"},"spec":null}\n"}, "creationTimestamp":"2019-11-28T13:10:18Z", "generation":1, "name":"deny-all", "namespace":"foo", "uid":"6cd403b8-11e0-11ea-b8c3-42010a210004"}, "spec":interface {}(nil)}: validation failure list:
    spec in body must be of type object: "null"

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Examples should work

**Steps to reproduce the bug**
Copy/paste example from documentation and try to apply it.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.4.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.14

**Comment by wereeder** [comment]
I see the same problem on this page: [https://istio.io/docs/reference/config/security/authorization-policy/](url). However, on this other blog post, it shows the deny-all Authorization Policy that works well: [https://istio.io/blog/2019/v1beta1-authorization-policy/](url). Here is the working deny-all rule, adding the {} after the spec:
`apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: deny-all
 namespace: foo
spec:
 {}
`

The documentation on the AuthorizationPolicy reference page needs to be updated.

**Comment by yangminzhu** [comment]
@wereeder I think https://github.com/istio/api/pull/1184 only changes the master branch which is for only showing in the preliminary doc: https://preliminary.istio.io/docs/reference/config/security/authorization-policy/

The PR should be cherry-picked to the release-1.4 branch, @rolandkool Do you think you have some time to do the cherry-pick? Thank you.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/api/pull/1184
