### ISSUE TITLE
gateways field in HTTPMatchRequest is undocumented, yet feature is used on docs site

### ISSUE THREAD

**Issue by selmanj** [istio/api#1198]
**Bug description**

(originally reported to me by @jcomputer)

Field `gateways` in HTTPMatchRequest is not documented:

https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L711

I understand fields that are undocumented are considered experimental. However the public docs use the 'gateways' field under HTTPMatchRequest in an example:

https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-http-traffic

Either we should label the usage of this field as experimental (which isn't currently mentioned on the docs page) or we should document the field.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by howardjohn** [comment]
this has a doc now
