### ISSUE TITLE
Regular expressions are not supported for across-domain

### ISSUE THREAD

**Issue by ZereChen** [istio/api#1199]
**Describe the feature request**
 Regular expressions are not supported for across-domain now.
**Describe alternatives you've considered**
AllowOrigin and AllowOriginRegex are deprecated in route.CorsPolicy. So we can use alloworiginStringMatch instead of them. because route.CorsPolicy has a variable alloworiginStringMatch,i want to add alloworiginStringMatch in networking.CorsPolicy. Exact is the same as AllowOrigin and regex is the same as AllowOriginRegex
see https://github.com/istio/api/pull/1197

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by howardjohn** [comment]
regex is allowed now: https://istio.io/latest/docs/reference/config/networking/virtual-service/#StringMatch
