### ISSUE TITLE
Add v prefixed release tags

### ISSUE THREAD

**Issue by jpreese** [istio/api#1201]
When consuming modules from Go, the Go toolchain expects tags to start with _v_. 

Going forward, could a tag be added that contains the v prefix? It would be nice to add some retroactively as well. Thanks!

**Comment by howardjohn** [comment]
Is `v` a hard requirement, I thought it supported both forms?

**Comment by jpreese** [comment]
It is a hard requirement. If the module that you're referencing does not have tags prefixed with v, it won't resolve correctly and some manual intervention is required.

**Comment by howardjohn** [comment]
Thanks, I didn't realize that. I think we have some code that expects to not have a v prefix, so we would need to have double tags probably.. or more precisely we have code that looks at the version string in the code. I supposed we could tag with `v` but set the version without `v`.

We do not follow proper semver though, so fixing this may cause some problems there as well

fyi @jasonwzm probably even more relevant for client-go

**Comment by jpreese** [comment]
client-go is also relevant. If you're trying to keep them in sync, double tagging may also help as client-go currently will keep grabbing the latest Istio API (references istio.io/api v0.0.0-20191109011911-e51134872853)

**Comment by howardjohn** [comment]
We would need to do more than double tagging for that right? eg if we release 1.5.1, we tag both repos v1.5.1, but then we need to update go.mod in client-go to point to istio.io/api@v1.5.1?

**Comment by jpreese** [comment]
That is correct, yes.

Right now I'm using client-go (which requires istio.io/api), but in my `go.mod` they have different dates on them. It hasn't caused any problems that I'm aware of, but just a thought if the goal is to keep them in sync.

my `go.mod`

```
...
	istio.io/api v0.0.0-20191205234547-d2b87eef5659
	istio.io/client-go v0.0.0-20191206191348-5c576a7ecef0
```

**Comment by jasonwzm** [comment]
For client-go which is user-facing, we can tag the repo with v versions. We can follow something here: https://github.com/kubernetes/client-go/blob/master/INSTALL.md#add-client-go-as-a-dependency

But for Istio internal usage of different go modules, we currently use sha to import a repo, which is intended.  For pseudo versions in go modules, the difference in timestamps are fine as long as they are using the correct sha for each repo.

@howardjohn can you help adding double tagging for client-go in the next release? I could not find the release checklist doc.

**Comment by howardjohn** [comment]
@jasonwzm its all automated in istio/release-builder. Under publish/github there should be stuff about tagging
