### ISSUE TITLE
Evaluate Kubernetes hierarchical namespace support

### ISSUE THREAD

**Issue by louiscryan** [istio/api#1205]
The Kubernetes multi-tenancy SIG is seriously looking at enabling hierarchy over namespaces.

https://docs.google.com/document/d/10MZfFfbQMm33CBboMq2bfrEtXkJQQT4-UH4DDXZRrKY/edit#heading=h.mjsh4dw4gklk

This feature if well supported could have many major benefits for Istio so is worthy of broader discussion. Some examples of features that could be influenced in no particular order:
- Use to control scoping of service visibility. E.g exportTo=some/non-leaf/namespace
- Authz ability to allow access to non-leaf identities. E.g. allow all in 'sales' organization
- Used to control composition of Authz policies
- Control plane instance sharding on organizational boundaries

Timeline for delivery is not entirely clear but work seems pretty active

**Comment by yangminzhu** [comment]
cc @yangminzhu

**Comment by howardjohn** [comment]
Hierarchical namespaces is dead now: https://github.com/kubernetes-retired/multi-tenancy/tree/master :slightly_frowning_face:
