### ISSUE TITLE
Extending StringMatch to support "if-not-present" in the header match

### ISSUE THREAD

**Issue by igsong** [istio/api#1220]
**Describe the feature request**

I would like to suggest to extend header match capability. For example, Route of Envoy is capable to express non-existence of a header, but Istio is not. In some case, an existence of a header is not acceptable to a specific endpoint.

One easy way is to add fields into StringMatch of VirtualService as follows:
```
// StringMatch of VirtualService
message StringMatch {
  oneof match_type {

    // exact string match
    string exact = 1;

    // prefix-based match
    string prefix = 2;

    // ECMAscript style regex-based match
    string regex = 3;

    // Newly added to express "present of a header"  
    bool present = 4;
  }

  reserved 5, 6, 7, 8;
  // Newly added to express negation
  bool invert = 9;
}
```

In addition, similar with above way, `suffix` matching may be able to be implemented.

**Describe alternatives you've considered**

What should be noted is that `StringMatch` is used for "header match" as well as "query parameter match", while the header match and query parameter match are differently handled by Envoy. 
(Basically, Envoy does not support `invert` semantics for the "query parameter match")

To keep consistency between Envoy and Istio, it would be better to define and use new data structure for the header match, in order to use different data structure for the header match and query parameter match.
However, it may cause incompatibility with previous API version, so I think that the addition of fields as above is easier way.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by rshriram** [comment]
this is fine but dont do it in string match as other fields like url match use it. One option is to create a richer HeaderMatch that has present and inverted. Another one is to do a not_match field with the old string match (and a not present field with just header names)

**Comment by igsong** [comment]
Thanks for comments! I'll make a pull request for this in several weeks.

**Comment by rshriram** [comment]
are you planning to send an istio API Pr for this as well ?

**Comment by igsong** [comment]
Do you mean that I have a plan for submitting PR to istio/istio regarding the changes happen on https://github.com/istio/api/pull/1233 ? If right, I will do soon after the changed version of API is properly included in istio/istio.

**Comment by igsong** [comment]
BTW, it would be better to keep this issue until corresponding changes is made on istio/istio.
