### ISSUE TITLE
Define general purpose and optimized read-only API for Galley

### ISSUE THREAD

**Issue by ayj** [istio/api#126]
The configuration component has two logical sets of APIs: the general purpose RESTful API and the more specialized read-only sync API for high throughput configuration consumers. Both are gRPC APIs.
 
The RESTful version of the general purpose API is provided by grpc-gateway and later possibly through envoy grpc transcoding. An overview of this method is documented here. 

ref https://docs.google.com/document/d/13UqmYpEjNGT2xucIgWaTQIQUgQuAASeIdm8Ks3zp5Fk/edit#bookmark=id.1ttx3vf6ypj2

**Comment by ayj** [comment]
cc @mandarjog

**Comment by geeknoid** [comment]
No longer relevant.
