### ISSUE TITLE
DestinaionRule LoadBalancer Field type mismatch

### ISSUE THREAD

**Issue by kentchenjh** [istio/api#1269]
unregular filed(ttl):
https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.proto#L348
https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.pb.go#L911

regular field(connect_timeout):
https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.proto#L436
https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.pb.go#L1062

according to the proto, these two fileds use the same type, although the generated pb tells a different story. Is something wrong when generating pb?

**Comment by hzxuzhonghu** [comment]
This is caused by `(gogoproto.stdduration) = true`

**Comment by kentchenjh** [comment]
The type of ttl is *time.Duration which equals to int64. The example(https://istio.io/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB-HTTPCookie) shows ttl contains time suffix. So which side is correct?

**Comment by kentchenjh** [comment]
@hzxuzhonghu take a look plz.

**Comment by hzxuzhonghu** [comment]
I an not sure why they are not same from original. I also think they should be of same type.

In addition, is there any usability for you now?

**Comment by kentchenjh** [comment]
Since I need pb.go file to generate java class, ttl would be translated into integer type in the end. Apparently "1ms" cannot be cast to integer. Should I raise a new PR to remove `(gogoproto.stdduration) = true` and regenerate destination rule pb.go?

**Comment by hzxuzhonghu** [comment]
Sure, welcome
