### ISSUE TITLE
Add objectMeta field to authorizationPolicy struct in the api

### ISSUE THREAD

**Issue by malizz** [istio/api#1303]
**Describe the feature request**
`ObjectMeta` field to be added to `AuthorizationPolicy` struct [here](https://github.com/istio/api/blob/master/security/v1beta1/authorization.pb.go#L229).
Similar to [Istio Go Client](https://github.com/istio/client-go/blob/master/pkg/apis/security/v1beta1/types.gen.go#L73)

This will ensure the api is consistent with the rest of the documentation. 

**Describe alternatives you've considered**
With objectMeta field missing, early validation of yaml in the pipeline fails. 

[x] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by howardjohn** [comment]
No Istio protobufs have objectmeta. So I don't think this is specific to AuthorizationPolicy? Can you explain a bit more how this is breakign you?

**Comment by malizz** [comment]
> No Istio protobufs have objectmeta. So I don't think this is specific to AuthorizationPolicy? Can you explain a bit more how this is breakign you?

It doesn't exactly break functionality but it's confusing that both the spec and the whole object are names the same.

**Comment by howardjohn** [comment]
I agree its confusing but unfortunately not much we can do about this; these decisions were made before istio/client-go was a thing leaving us in an awkward state
