### ISSUE TITLE
Unable to use latest client-go with older istio

### ISSUE THREAD

**Issue by ryandawsonuk** [istio/api#1382]
In our operator we're [importing a recent version of the istio go client](https://github.com/SeldonIO/seldon-core/blob/master/operator/go.mod#L17). What we're finding is that this is incompatible with older versions of istio.

Specifically we're running istio 1.1.6 in a cluster with knative 0.11.1 and noticing that there are VirtualServices created by knative that have `websocketUpgrade: true` set [under the `http` section](https://github.com/kubeflow/kfserving/pull/125#discussion_r288382253). This leads to an issue as that [field was removed from the API](https://github.com/istio/api/pull/804). So in our operator using the istio client-go we get errors that look like

```
E0414 16:14:15.881377       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList.Items: []v1alpha3.VirtualService: v1alpha3.VirtualService.v1alpha3.VirtualService.Spec: unmarshalerDecoder: unknown field "websocketUpgrade" in v1alpha3.HTTPRoute, error found in #10 byte of ...|e":true}]}},{"apiVer|..., bigger context ...|:100}],"timeout":"600s","websocketUpgrade":true}]}},{"apiVersion":"networking.istio.io/v1alpha3","ki|...
```
We're not actually specifically trying to read those knative-created VirtualServices. Just the fact they exist breaks our operator when importing the new istio go client code.

We're having to downgrade the version of the istio go client that we use. Basically the change is a breaking change from the perspective of the go client. Was that intended when the field was deprecated and removed that the new go client would not be able to work with previous versions?

**Comment by jasonwzm** [comment]
Thanks for raising the issue. Right now the go client is generated according to the APIs. We recommend that you use the go client version that aligns with the Istio version you are using, so that they don't have mismatching fields. We are in the process of adding support of multi version of our APIs, so hopefully this will not be an issue in upcoming releases.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/tools/pull/1231
