### ISSUE TITLE
Standardize mixer and proxy protobuf definitions in istio/api

### ISSUE THREAD

**Issue by sakshigoel12** [istio/api#147]
@vadimeisenbergibm commented on [Mon Aug 14 2017](https://github.com/istio/istio/issues/557)

Currently, mixer uses "Required", while proxy used "REQUIRED". Should be "Required" in both.

---

@vadimeisenbergibm commented on [Mon Aug 14 2017](https://github.com/istio/istio/issues/557#issuecomment-322183342)

Following @ZackButcher's proposal.

---

@ldemailly commented on [Wed Aug 16 2017](https://github.com/istio/istio/issues/557#issuecomment-322936010)

similar to target/destination issue? we should get all the renames in before 0.2 ?

---

@rshriram commented on [Wed Aug 16 2017](https://github.com/istio/istio/issues/557#issuecomment-322955358)

please move to istio/api

---

@sakshigoel12 commented on [Wed Aug 16 2017](https://github.com/istio/istio/issues/557#issuecomment-322961789)

rshriram@ - if you are using zenhub there is an option to move issues between repos on the right pane (last option). It would be easier to not close and reopen issues.

**Comment by ldemailly** [comment]
originally in https://github.com/istio/istio/issues/557

**Comment by kyessenov** [comment]
deficiencies of proto documentation tooling. patched by hand.
