### ISSUE TITLE
LbPolicy without json tag.

### ISSUE THREAD

**Issue by FqqCS** [istio/api#1482]
**Bug description**
I use "DestinationRule" as a filed in my custom resource.
there is a error while generate crd  using controller-gen . the reason looks like  struct field "LbPolicy" without a JSON tag.

Error Msg:
```
/networking/v1alpha3/destination_rule.pb.go:814:2: encountered struct field "LbPolicy" without JSON tag in type "LoadBalancerSettings"
```
Only has protobuf tag for LbPolicy
```
type LoadBalancerSettings struct {
	// Upstream load balancing policy.
	//
	// Types that are valid to be assigned to LbPolicy:
	//	*LoadBalancerSettings_Simple
	//	*LoadBalancerSettings_ConsistentHash
	LbPolicy isLoadBalancerSettings_LbPolicy `protobuf_oneof:"lb_policy"`
	// Locality load balancer settings, this will override mesh wide settings in entirety, meaning no merging would be performed
	// between this object and the object one in MeshConfig
	LocalityLbSetting    *LocalityLoadBalancerSetting `protobuf:"bytes,3,opt,name=locality_lb_setting,json=localityLbSetting,proto3" json:"locality_lb_setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}
```

**Comment by shamsher31** [comment]
This is a known issue in `protobuf` lib, see https://github.com/golang/protobuf/issues/140,  https://github.com/golang/protobuf/issues/446

> The correct way to serialise a protocol buffer to JSON is to use the jsonpb package, which doesn't use the json struct field tags



Unfortunately, istio [don't unmarshal](https://github.com/istio/istio/blob/748c6209f606fb2276bdd4abaf277d4979d172bc/pilot/pkg/networking/core/v1alpha3/cluster.go#L835) `LbPolicy` but rather [call envoy cluster v3 API](https://github.com/envoyproxy/go-control-plane/blob/master/envoy/config/cluster/v3/cluster.pb.go#L467) which takes care of unmarshaling.

**Comment by zackzhangkai** [comment]
Hi, what's going on this? I have encountered the same problem.

**Comment by howardjohn** [comment]
This is working as expected. You cannnot use `encoding/json` with protobuf structs. Rather, you should use `jsonpb`.

**Comment by davidxia** [comment]
I'm trying to use Istio resources like AuthorizationPolicy in my kubebuilder's custom type and am getting `encountered struct field ... without JSON tag` when I run `make`.

`/Users/dxia/src/go/pkg/mod/istio.io/api@v0.0.0-20230512140303-8ba6dc2ef1d7/security/v1beta1/authorization_policy.pb.go:357:2: encountered struct field "state" without JSON tag in type "AuthorizationPolicy"`

What's the right way to do this?

**Comment by hzxuzhonghu** [comment]
You can use istio client-go directly instead
