### ISSUE TITLE
Doc broken for WorkloadSelector

### ISSUE THREAD

**Issue by psibi** [istio/api#1511]
**Bug description**

In the PeerAuthentication (and possibly other pages), the doc is broken for Workload Selector: https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

The link should go to an actual HTML page which exists. :-)

**Steps to reproduce the bug**

1. Go to https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication
2. Scroll down and try finding the link for `WorkloadSelector`
3. Click that link
4. Shows 404 Page

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

It's a docs issue, not required.

**How was Istio installed?**

It's a docs issue, not required.

**Environment where bug was observed (cloud vendor, OS, etc)**

It's a docs issue, not required.

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/api/pull/1540
