### ISSUE TITLE
Configuration access control

### ISSUE THREAD

**Issue by kyessenov** [istio/api#155]
In 0.2, we're adding more flexible selectors to route rules that allow arbitrary matches on the source and destination services. The structure roughly corresponds to:
```yaml
namespace: wildcard
source:
  name: x
destination:
  name: y
```
(the idea being that the source and destination inherit the rule namespace `wildcard` in every namespace)

How do we setup permissions to control who is allowed to edit this configuration?
It seems like we need some sort of meta-attribute reasoning - a decision is made based on what attributes are referenced in the rule and what the predicate values correspond to those attributes. For this example, the permissions are:
1. edit client-side configuration of service x in any namespace
2. edit server-side configuration of service y in any namespace
3. edit routes x to y in any namespace

Note that we are not yet enforcing bijection between namespaces and the organizational structure. A namespace here can be an application, an org, or a replica, and is not tied to an organizational unit.

Thoughts? @mandarjog @frankbu @rshriram @geeknoid

**Comment by geeknoid** [comment]
​This issue applies to all Istio resources. The solution is relatively
simple:

   - As normal, use namespace-level access control to protect individual
   resources.


   - Restrict which namespace can affect which service. Basically, we
   ordain in which namespace we look for the resources affecting the behavior
   of a particular service, and this provides a sufficient constraint to let
   operators manage who can impact a service.

The forced selection of namespaces is also how we achieve a "hierarchy" of
control. We look in a service-specific namespace, and then in a global
namespace for the resources.
​

**Comment by kyessenov** [comment]
That would require certain amount of encapsulation by the namespace. Imagine a route rule that controls traffic between two services in two distinct namespaces. We could say that rules like this must respect the namespace boundaries and be in some ways limited as opposed to rules within a namespace, which would enforce encapsulation. Or we could also same amount of expressivity to the rule, in which case it would be hard to pinpoint the rule to any namespace (client or server side namespace). The latter means a rule in any namespace can affect traffic flowing in or out of a particular namespace.

**Comment by geeknoid** [comment]
Even though we physically implement routing rules on the client-side, I
believe that many times these rules should logically be owned by the
destination service and not the source. This again highlights the need to
separate the manifestation of rules that the operators manipulates vs. what
we actually deliver to the proxy.

In other words, we need to look at the rule constructs and decide which
kind of rules is really about affecting a source service and hence should
be controlled by the source service's operator, whereas which rules should
be controlled by the destination service's operator. This then dictates
which namespace those rules should be located. It also imposes a
requirement on us to only look in the appropriate namespace for each kind
of rule.

**Comment by geeknoid** [comment]
Tracked elsewhere
