### ISSUE TITLE
Need clarification on maxRetries

### ISSUE THREAD

**Issue by linsun** [istio/api#1632]
**Bug description**

Our maxRetries (https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.proto#L616) is confusing - it is unclear if it applies to HTTP only or if it applies to other protocols as well.  The fact we had `max_retries` under `HTTPSettings` made me think it is for http only.  However, from [Envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto.html?highlight=max_retries#circuit-breakers), it seems to not only applies to HTTP and it applies to the upstream cluster without a specific protocol called out.

cc @GregHanson @frankbu @rshriram @howardjohn @lizan @PiotrSikora @louiscryan @nrjpoddar @ramaraochavali 

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ramaraochavali** [comment]
Yes. Max Retries is just applicable to Http - there are no retries for other protocols.

**Comment by linsun** [comment]
@ramaraochavali thank you very much - this is helpful!

**Comment by linsun** [comment]
Close this, as our doc is fairly clear
