### ISSUE TITLE
Could not access VirtualService with Istio Client.go API

### ISSUE THREAD

**Issue by barryzhounb** [istio/api#1633]
**Bug description**
I want to use Istio client.go API to access VirtualService, my code as following:

```
	istioNetworkingv1alpha3 "istio.io/api/networking/v1alpha3"

    istioVirtualService := &istioNetworkingv1alpha3.VirtualService{}
	err = r.Get(context.TODO(), types.NamespacedName{Name: instance.Name, Namespace: instance.Namespace}, istioVirtualService)
	if err != nil && errors.IsNotFound(err) {
	    //New VirtualService
	    log.Info("Not found Istio VirtualService.")
	} else {
	    log.Info("Found Istio VirtualService.", "Gateways= ", istioVirtualService.Gateways[0])
	}
```

It failed to access VirtualService, the failure was:

```
cannot use istioVirtualService (type *v1alpha3.VirtualService) as type runtime.Object in argument to r.Client.Get:
	*v1alpha3.VirtualService does not implement runtime.Object (missing DeepCopyObject method)
```

[ x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
VirtualService resource can be accessed successfully.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio V1.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
You should be using the VirtualService from istio/client-go.
The VirtualService from istio/api is the `spec` field, not the full
kubernetes object

**Comment by barryzhounb** [comment]
Hi @howardjohn  , I followed the link https://github.com/istio/client-go, and get go module with command "go get istio.io/client-go@master". I think api should be "istio.io/api/networking/v1alpha3", because in go.mode, it is defined as "module istio.io/client-go".

What do you mean "istio/client-go"? could you explain what should I use?

**Comment by barryzhounb** [comment]
Thanks @howardjohn . Could you let me know where I can find some example code or test code for creating  a VirtualService?
