### ISSUE TITLE
`make gen` is not deterministic

### ISSUE THREAD

**Issue by howardjohn** [istio/api#1678]
It is an extremely common issue where `make gen` is not matching CI. I think its some makefile madness where it detects files are not changed so it skips them, but the makefile does not properly declare all dependencies (the version of the tools, for example) so they are skipped.

We need to make it so that `make gen` ALWAYS matches the output of CI, or the dev ex is horrible.

**Comment by howardjohn** [comment]
Example:

I ran `make gen` after a tooling update to the json generated output. CI shows diff:
```
	modified:   analysis/v1alpha1/message_json.gen.go
	modified:   authentication/v1alpha1/policy_json.gen.go
	modified:   meta/v1alpha1/status_json.gen.go
	modified:   security/v1alpha1/ca_json.gen.go
	modified:   type/v1beta1/selector_json.gen.go
```

Then I deleted all of the json.gen.go (`find | rg json.gen.go | xargs rm)`, and reran. 

Now, I get a bunch of deleted files!:
````
        deleted:    analysis/v1alpha1/message_json.gen.go
        modified:   authentication/v1alpha1/policy_json.gen.go
        deleted:    meta/v1alpha1/status_json.gen.go
        deleted:    operator/v1alpha1/operator_json.gen.go
        deleted:    security/v1alpha1/ca_json.gen.go
        deleted:    security/v1beta1/authorization_policy_json.gen.go
        deleted:    security/v1beta1/jwt_json.gen.go
        deleted:    security/v1beta1/peer_authentication_json.gen.go
        deleted:    security/v1beta1/request_authentication_json.gen.go
        deleted:    type/v1beta1/selector_json.gen.go
```

Based on this, I think the generation code for security, operator, and analysis has some issues.

**Comment by sdake** [comment]
The idea of `make gen` is that `make clean` is always run prior to `make gen`. This will result in deterministic results. It is not ideal, although this is a limitation of the build system. One option is to enforce a dependency on clean prior to `make gen`. In CI and developer environments.

**Comment by jasonwzm** [comment]
+1 to Steven's comment. Running `make clean` before `make gen` is always suggested.

**Comment by kyessenov** [comment]
Sorry for bringing this is up, but this is a solved problem with bazel.

**Comment by howardjohn** [comment]
https://github.com/istio/api/pull/1833
