### ISSUE TITLE
Issue with docs/reference/config/istio.mesh.v1alpha1/index.html

### ISSUE THREAD

**Issue by hobbytp** [istio/api#1709]
For "terminationDrainDuration" parameter description, please add one note here, the biggest duration is less than the kubernetes kubelet grace termination period ( terminationGracePeriodSeconds), the default is 30seconds (can find info here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)

**Comment by ericvn** [comment]
This reference document is pulled from https://github.com/istio/api/blob/master/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
