### ISSUE TITLE
Remove unused annotations

### ISSUE THREAD

**Issue by nmittler** [istio/api#1738]
There are several annotation that are no longer used. They should be removed.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Everything on https://istio.io/latest/docs/reference/config/annotations/ seems used,  so I think we did this at some point
