### ISSUE TITLE
Add annotation feature status "RETIRED"

### ISSUE THREAD

**Issue by nmittler** [istio/api#1746]
This feature status would indicate that the annotation is beyond simply deprecated, but is no longer used.

We would likely not want to document RETIRED values (on istio.io), but retain them for our tooling.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by nrjpoddar** [comment]
Can you define what’s the semantic difference between RETIRED and DEPRECATED and I’m assuming there’s a progression here from one to the other.

**Comment by nmittler** [comment]
@nrjpoddar that sounds right to me.

@louiscryan can you confirm?

**Comment by nmittler** [comment]
reassigning to @brian-avery who is taking over this work.
