### ISSUE TITLE
ProxyConfig.concurrency documentation is unclear

### ISSUE THREAD

**Issue by CAFxX** [istio/api#1783]
**Bug description**

`istio.mesh.v1alpha1.ProxyConfig.concurrency` documentation is unclear

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

The docs should not contain self-contradictions, especially in the same paragraph. :)

**Steps to reproduce the bug**

Visit https://istio.io/v1.8/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig, rendered from https://github.com/istio/api/blob/c2df7c41fd8e4f27ef9aea3bdbcd1fa1eede4a00/mesh/v1alpha1/proxy.proto#L372-L376

Notice that the comment for `concurrency` is self-contradicting:

> The number of worker threads to run. 
> **If unset**, this will be automatically determined based on CPU requests/limits. 
> If set to 0, all cores on the machine will be used. 
> **Default** is 2 worker threads.

since it claims that there are two different behaviors for the same case ("if unset" and "default"), something that should be impossible outside of quantum computing. In our deployments at least it seems that the actual behavior is the latter (2 worker threads). The apparent self-contradiction was added in #1493. 

It is also possible we're simply misinterpreting the comment, but then in this case we really have no idea of what the correct meaning could be.

There is a separate point to be made about the sanity of such a default (arguably automatically calculating it as in the former case would make more sense), but let's focus on at least getting the docs right for now. Likely related: https://github.com/istio/istio/issues/23470.

cc @shamsher31 @howardjohn

**Comment by howardjohn** [comment]
Sent out https://github.com/istio/api/pull/3193

**Comment by howardjohn** [comment]
BTW: the quantum mechanics of unset != default is (at least now - its changed since 2020) somewhat correct but highly confusing; we default the limit to 2, and unset uses limits, so default is 2.
