### ISSUE TITLE
releaselocks missing for 1.7+

### ISSUE THREAD

**Issue by howardjohn** [istio/api#1814]
```
$ ls releaselocks
release-1.0/  release-1.1/  release-1.2/  release-1.3/  release-1.4/  release-1.5/  release-1.6/
```

Seems like we should be updating these? cc @jasonwzm

**Comment by jasonwzm** [comment]
It is an item to release checklist e.g. https://github.com/istio/istio/issues/27993

I will manually add.

**Comment by howardjohn** [comment]
these are removed
