### ISSUE TITLE
Cleanup deprecated docs and files

### ISSUE THREAD

**Issue by douglas-reid** [istio/api#182]
There is a bunch of stuff in this repo that no longer is relevant.  We need to clean it up.

Need to update:
- [ ] api/mixer/v1/config/

**Comment by sakshigoel12** [comment]
@ZackButcher @douglas-reid The PR is merged. anything more we want to clean up before release?

**Comment by sakshigoel12** [comment]
@douglas-reid  can you check if this is done and close the issue?
