### ISSUE TITLE
Fix comments in mixer/v1/config/cfg.proto

### ISSUE THREAD

**Issue by douglas-reid** [istio/api#184]
The examples and comments for messages like Instance and Handler are no longer correct or valid.

**Comment by guptasu** [comment]
Are they not valid because they in not in CR form ? Or there is something else missing ?

**Comment by geeknoid** [comment]
Can this be closed? Are the examples correct at this point?

**Comment by douglas-reid** [comment]
I think most of the problematic bits can be removed as part of the removal of all the long-deprecated bits.

I also think it probably makes sense to update the examples for the bits that remain to match the CR form that we expect operators to interact with.
