### ISSUE TITLE
Update status of label service.istio.io/canonical-name

### ISSUE THREAD

**Issue by nmittler** [istio/api#1850]
https://github.com/istio/api/blob/master/label/labels.yaml

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by EronWright** [comment]
@nmittler what is the feature status of this label, `Beta`?  Someone else could maybe pick up this issue.

**Comment by nmittler** [comment]
@EronWright I have no idea, hence the issue :). This bug was effectively created to get someone to look at it and make that determination.
