### ISSUE TITLE
Issue with docs/reference/config/networking/gateway/index.html

### ISSUE THREAD

**Issue by farcaller** [istio/api#1892]
ServerTLSSettings.credentialName states:

> For gateways running on Kubernetes, the name of the secret that holds the TLS certs including the CA certificates. Applicable only on Kubernetes. The secret (of type generic) should contain the following keys and values: key: <privateKey> and cert: <serverCert>. For mutual TLS, cacert: <CACertificate> can be provided in the same secret or a separate secret named <secret>-cacert. Secret of type tls for server certificates along with ca.crt key for CA certificates is also supported. Only one of server certificates and CA certificate or credentialName can be specified.

It seems that the keys aren't correct (or are partially incorrect), as istio will ingest keys `tls.crt` / `tls.key` for a secret of type `kubernetes.io/tls`.

This documentation is also missing a crucial point that the secret referenced in credentialName must reside in the same namespace as the ingress gateway.

**Comment by howardjohn** [comment]
"Secret of type tls for server certificates along with ca.crt key for CA certificates is also supported." is intending to cover this. It should probably say 

"Secret of type kubernetes.io/tls, with keys tls.crt and tls.key for server certificates, along with ca.crt key for CA certificates is also supported."

**Comment by howardjohn** [comment]
This has been updated at some point to include this
