### ISSUE TITLE
Issue with docs/reference/config/istio.operator.v1alpha1/index.html

### ISSUE THREAD

**Issue by dsbos** [istio/api#1905]
The section at https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#K8sObjectOverlay-PathValue says:

> All values are strings but are converted into appropriate type based on schema.

That would probably be clearer (and be consistent with the style of the preceding text) if it said:

> All values are strings but are converted into the appropriate type based on the schema.

(Or maybe "... based on schemas" (well, formally, "schemata"), if that reflects the author's intended meaning better.)

**Comment by esnible** [comment]
@ostromart Tentatively assigning to you.  Feel free to reassign, unassign, or close.

**Comment by ostromart** [comment]
Thanks for reviewing and bringing this up @dsbos. Would you be interested in contributing some PR's to improve the docs, for this any any other issues you find?
