### ISSUE TITLE
Importing service with tls mode=DISABLED will be ignored

### ISSUE THREAD

**Issue by monsteredc** [istio/api#1927]
**Bug description**
When trying to add a new destination rule with the tls setting configured in the traffic policy part as `mode: DISABLED`, the `ClientTLSSettings_TLSmode` attribute in `networking/v1alpha3/destination_rule.pb.go` needs to be set to `ClientTLSSettings_DISABLE ClientTLSSettings_TLSmode = 0`. However, after doing the json.Marshal function, the zero value will be ignored because of the `omitempty` property. As a result, the tls setting will become empty like this:
```
trafficPolicy:
    tls: {}
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
tls mode=DISABLED
**Steps to reproduce the bug**
N/A
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
N/A
**How was Istio installed?**
N/A
**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

**Comment by howardjohn** [comment]
DISABLE is the zero value. `tls: {}` and `tls: { mode: DISABLE }` _should_ be identical. Is this not the case?

**Comment by monsteredc** [comment]
@howardjohn Thanks! I'll close the issue.
