### ISSUE TITLE
sourceLabels doc. seems unclear in docs/reference/config/networking/virtual-service/index.html

### ISSUE THREAD

**Issue by dsbos** [istio/api#1930]
In the section currently at https://istio.io/latest/docs/reference/config/networking/virtual-service/#L4MatchAttributes-source_labels,
where the text says:

> One or more labels that constrain the applicability of a rule to workloads with the given labels.

it's not clear whether that "workloads with the given labels" applies to the workloads for _calling_ services or to workloads for _called_ services.

(Yes, the name `sourceLabels` _suggests_ that it's for calling services, but the text doesn't seem to actually confirm that.)

(Also, the wording "labels that constrain the applicability of a rule to workloads" is quite abstract and doesn't really specify much.  It should probably mention something like "selecting workloads with the corresponding labels" (maybe also referring to a similar member, such as "&lt;something>'s `selector`" (or `workloadSelector`)).)

**Comment by ericvn** [comment]
Note that the changes should made in the main branch and cherry-picked to the release-1.9 branch where they will eventually be merged into istio.io docs.
