### ISSUE TITLE
OS X Build broken

### ISSUE THREAD

**Issue by rshriram** [istio/api#200]
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(atomicops_internals_x86_msvc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
INFO: From ProtoCompile google/rpc/status.pb.go:
../../external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mixer/v1/attributes.pb.go:
../../external/com_github_gogo_protobuf: warning: directory does not exist.
../../external/com_google_protobuf/src: warning: directory does not exist.
../../external/com_github_googleapis_googleapis: warning: directory does not exist.
INFO: From ProtoCompile mixer/v1/template/extensions.pb.go:
../../external/com_google_protobuf/src: warning: directory does not exist.
ERROR: istio.io/api/mixer/v1/BUILD:3:1: GoCompile mixer/v1/~lib~/go_default_library.o failed (Exit 1).
2017/10/12 15:24:39 missing strict dependencies:
	bazel-out/darwin_x86_64-fastbuild/genfiles/mixer/v1/check.pb.go: import of istio.io/api/google/rpc, which is not a direct dependency
INFO: Elapsed time: 142.443s, Critical Path: 12.10s

**Comment by kyessenov** [comment]
i'll get to that once I unblock folks depending on api

**Comment by rshriram** [comment]
fixed..
