### ISSUE TITLE
Broken link to Envoy TLS context

### ISSUE THREAD

**Issue by birbilis** [istio/api#2015]
Broken link "TLS context" 
at phrase "ClientTLSSettings SSL/TLS related settings for upstream connections. See Envoy’s TLS context for more details." 
in https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings

currently points to broken URL:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html

**Comment by chadlwilson** [comment]
Thank you @ericvn !
