### ISSUE TITLE
Doc.: 'The format is “[/]”'  on Global Mesh Options page.

### ISSUE THREAD

**Issue by dsbos** [istio/api#2033]
The row currently at https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider-service, along with several others, says:

> The format is “[/]”. 

That doesn't make any sense.

From looking at the raw (source) HTML, it seems that someone forgot to encode certain "<" characters in your documentation source, and that that someone didn't even look at the rendered output after making changes.

**Comment by yangminzhu** [comment]
I don't think we should encode the "<" character in the protobuf file. It should be the html generation tool's responsibility to handle these issues.
But I think it's probably better and much easier to just quote the string with the ` character, will send out a PR.
