### ISSUE TITLE
Make gen failed after https://github.com/istio/api/pull/2044

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/api#2045]
**Bug description**
# make gen
...
./gen.sh: line 23: buf: command not found
make[1]: *** [Makefile.core.mk:37: gen-proto] Error 127

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This should be fixed now, thanks!
