### ISSUE TITLE
[Question] Istio Operator (CR) API version resource

### ISSUE THREAD

**Issue by yonicurv** [istio/api#2057]
https://github.com/istio/api/blob/b719f46511e4d27b4b78d135296c5893863e1f16/operator/v1alpha1/operator_json.go#L20

Hey,

I have a question regarding Istio operator component and api custom resources it comes with.
At any documentation im seeing (Google or Istio) I can see only reference to Istio operator v1alpha1

I would like to know wether it is GA ?
When its expected to have a beta or final api release for that CR ?

Thanks,
Jony.

**Comment by howardjohn** [comment]
Plans to move this to beta have not begun. If you are interested in this, they best place to follow is the Environments working group (https://docs.google.com/document/d/1Ot9AeoiNYnI3fbQrq3w_-cyGxOqS8AD0RChkQfVxyhs or #environments on slack)

**Comment by howardjohn** [comment]
This is unlikely to ever happen given recent directions
