### ISSUE TITLE
ModuleNotFoundError: No module named 'gogoproto'

### ISSUE THREAD

**Issue by triThirty** [istio/api#2149]
**Bug description**
When I run `from mcp_pb2 import RequestResources` under `python/istio_api/mcp/v1alpha1` directory, I got `ModuleNotFoundError: No module named 'gogoproto'`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience

**Expected behavior**
Can import `RequestResources` correctly.
**Steps to reproduce the bug**
```BASH
$ cd python/istio_api/mcp/v1alpha1
$ python
Python 3.8.9 (default, Aug  3 2021, 19:21:54)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcp_pb2 import RequestResources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/I548273/code/test/gRPC/api/python/istio_api/mcp/v1alpha1/mcp_pb2.py", line 15, in <module>
    from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
ModuleNotFoundError: No module named 'gogoproto'
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
It's master branch

**Comment by howardjohn** [comment]
This code is removed
