### ISSUE TITLE
Partition API by functional/feature area instead of components

### ISSUE THREAD

**Issue by kyessenov** [istio/api#219]
Rename `pilot` to `routing`.
Split `mixer` into `telemetry`, `security`, and `mixerapi`.

cc @geeknoid @rshriram

**Comment by geeknoid** [comment]
As mentioned in the Repo Update doc, Mixer will have a trivial amount of config state in here and there's actually nothing to partition. Mixer config is described via templates and adapter-specific config protos, neither of which appear in this repo.

So we probably want simply:

istio/api/<component>/<component-specific api protos>
istio/api/<config>

**Comment by kyessenov** [comment]
This is fixed.
