### ISSUE TITLE
Should we include .pb.go files in this repository?

### ISSUE THREAD

**Issue by kyessenov** [istio/api#22]
I think there is a lot of value in providing generic go tooling support in terms of IDE support, simple `go get` command working. Every go tool expects the code to be buildable on its own without requiring bazel build tool. Why don't we follow the convention and include the generated code here?
We can check consistency with a simple CI test validating code generation.

**Comment by mandarjog** [comment]
There are a few cases where this is inevitable. We have come across 1 case so far.
https://github.com/istio/mixer/issues/134

protoc-go does not support parsing of ptypes.Struct. The generated code had to be fixed up before compiling. It was easier in this case to check-in the generated code.
