### ISSUE TITLE
protoc version error

### ISSUE THREAD

**Issue by zirain** [istio/api#2235]
**Bug description**

protoc version change to unknow after `make gen`

![image](https://user-images.githubusercontent.com/4354057/152896050-b8cad401-d766-4d51-89f5-e21a019eb76f.png)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience

**Comment by howardjohn** [comment]
This is intended from https://github.com/istio/tools/commit/250e4c466b8965ea2ca54d435dcbe2397f3c1469. but it was supposed to run `make gen` and commit it, so we need to do it manually I guess. Not sure why it did not do it automatically

**Comment by zirain** [comment]
> This is intended from [istio/tools@250e4c4](https://github.com/istio/tools/commit/250e4c466b8965ea2ca54d435dcbe2397f3c1469). but it was supposed to run `make gen` and commit it, so we need to do it manually I guess. Not sure why it did not do it automatically

protoc version seems incorrect after manual run `make gen`
