### ISSUE TITLE
Egress - VirtualService Route Destination Host "TLD cannot be all-numeric"

### ISSUE THREAD

**Issue by aeci-nre** [istio/api#2260]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
When specifying an IP address within a VirtualService Route Destination Host field I am met with the below error:

Error from server: error when creating "istio-egress.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: domain name "168.0.10" invalid (top level domain "10" cannot be all-numeric)

**Affected product area (please put an X in all that apply)**

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
IP addresses are allowed to be matched against within "sniHosts" and used as spec.hosts criteria. I would expect to be able to not only match based on a destination IP address but also specify an IP address for destination routing.

**Steps to reproduce the bug**
Specify an IP address in the "VirtualService.spec.tls.route.destination.host" field

Attempt to apply the attached yaml text file to see the error.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Running in MicroK8s

istio api v1beta1 and v1alpha3

istioctl version --remote:
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (8 proxies)

kubectl version:
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.3-2+d441060727c463", GitCommit:"d441060727c4632b67d09c9118a36a8590308676", GitTreeState:"clean", BuildDate:"2022-01-26T22:01:35Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.3-2+d441060727c463", GitCommit:"d441060727c4632b67d09c9118a36a8590308676", GitTreeState:"clean", BuildDate:"2022-01-26T21:57:05Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
MicroK8s enable Istio add-on

**Environment where bug was observed (cloud vendor, OS, etc)**
MicroK8s on metal (Ubuntu 20.04)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
[egress-test-vs-yaml.txt](https://github.com/istio/api/files/8172391/egress-test-vs-yaml.txt)

**Comment by howardjohn** [comment]
This is working as intended, the TLS spec explicitly says IP addresses are not allowed in SNI
