### ISSUE TITLE
Why istio api types have proto unexported fields

### ISSUE THREAD

**Issue by masquee** [istio/api#2538]
For example, ServiceEntry has unexported fileds 

```
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
```

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/8470824/199384845-5d72387c-21ee-419f-8200-118a85e6e23c.png">

And Kubernetes native types have no these unexported fields, for example `PodSpec`

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/8470824/199384898-930d71d0-e8ba-45bf-a232-c1dbf7eb108a.png">

**Why I care about this**

Recently I use kubernetes `equality.Semantic.DeepEqual` compare two ServiceEntry but got a panic

```
panic: an unexported field was encountered, nested like this:  [recovered]
	panic: an unexported field was encountered, nested like this: int32 [recovered]
	panic: an unexported field was encountered, nested like this: v1beta1.ServiceEntry -> int32 [recovered]
	panic: an unexported field was encountered, nested like this: *v1beta1.ServiceEntry -> v1beta1.ServiceEntry -> int32 [recovered]
	panic: an unexported field was encountered, nested like this: *v1beta1.ServiceEntry -> v1beta1.ServiceEntry -> int32
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by howardjohn** [comment]
This is how protobuf works: https://github.com/golang/protobuf

Use cmp.Equal(a,b,protocmp.Transform), not DeepEqual.

**Comment by michaelbannister** [comment]
I just started seeing this error upon updating a controller which I'm using to manage VirtualService and ServiceEntry.

The controller is built using controller-runtime (from kubebuilder) and [its CreateOrUpdate utility function](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L215) uses `equality.Semantic.DeepEqual`.

The error started when updating controller-runtime from v0.13.1 to v0.14.0, which bumped a few other versions:
```diff
 require (
        github.com/coderanger/controller-utils v0.0.0-20201221100905-e26c5734ecc9
-       github.com/google/go-cmp v0.5.8
+       github.com/google/go-cmp v0.5.9
        istio.io/api v0.0.0-20230125212921-f04847bedb29
        istio.io/client-go v1.16.2
-       k8s.io/api v0.25.0
-       k8s.io/apimachinery v0.25.0
-       k8s.io/client-go v0.25.0
-       sigs.k8s.io/controller-runtime v0.13.1
+       k8s.io/api v0.26.1
+       k8s.io/apimachinery v0.26.1
+       k8s.io/client-go v0.26.1
+       sigs.k8s.io/controller-runtime v0.14.0
 )
```
but the CreateOrUpdate function didn't change, and I'm still trying to work out _what_ changed that could have affected the behaviour in this way. So not sure whether to raise this in controller-runtime or some other project!

Mentioning it here in case the OP has solved it or anyone else has found the same, or has any pointers on where to look. Meanwhile I'll try & reduce the problem to a minimal reproduction that I can share.

FYI @gideshrp

**Comment by howardjohn** [comment]
Istio changed to use protobuf v2 is what make it have unexported fields.

**Comment by masquee** [comment]
`cmp.Equal` seems to have serious performance issues and is not suitable for production use.

![image](https://user-images.githubusercontent.com/8470824/217727133-c1282685-5a37-4a13-862e-763a22c929fd.png)

---

Finally I use `proto.Equal` from package `google.golang.org/protobuf/proto`.

**Comment by michaelbannister** [comment]
I figured out how to wire this into a controller-runtime manager:

```go
// SetupWithManager sets up the controller with the Manager.
func (r *MyCustomResourceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	// Add support for comparing istio types
	_ = equality.Semantic.AddFunc(func(vs1, vs2 *v1beta1.VirtualService) bool {
		return cmp.Equal(&vs1.Spec, &vs2.Spec, protocmp.Transform())
	})
	_ = equality.Semantic.AddFunc(func(vs1, vs2 *v1beta1.ServiceEntry) bool {
		return cmp.Equal(&vs1.Spec, &vs2.Spec, protocmp.Transform())
	})

	return ctrl.NewControllerManagedBy(mgr).
		For(&crdv1.MyCustomResource{}).
		Owns(&v1beta1.VirtualService{}).
		Owns(&v1beta1.ServiceEntry{}).
		Complete(r)
}
```
