### ISSUE TITLE
Error generating CUE from proto

### ISSUE THREAD

**Issue by HarithaPatchari054** [istio/api#2620]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Facing issue while running make command
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master
**How was Istio installed?**
Cloning the repo
**Environment where bug was observed (cloud vendor, OS, etc)**
linux putty
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Aside from no real info here, we moved off cue. So I think this is obsolete
