### ISSUE TITLE
Revise DestinationPolicy

### ISSUE THREAD

**Issue by louiscryan** [istio/api#270]
@rshriram @ZackButcher 

DestinationPolicy is a decorator for a service declared in the service registry. Its responsibility is to describe common policy that should be used when talking to all endpoints within that service. As such it defines timeouts, retries, hashing of endpoints for affinity/sharding etc.

A DestinationPolicy can be defined to match a DNS wildcard prefix so that a single policy can be applied to many services within a cluster / namespace etc.

TODO:

- Align file and schema organization with the above concept & cleanup docs / comments
- How does policy inherit
- Address how weighting, hashing and sharding are addressed within a service
- Evaluate how to create named subsets within a service to simplify routing.

**Comment by geeknoid** [comment]
Can we close this?
