### ISSUE TITLE
vivox80pro.mx@gmail.com

### ISSUE THREAD

**Issue by vivox80pro** [istio/api#2724]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[apply] Configuration Infrastructure
[apply] Docs
[apply] Installation
[apply] Networking
[apply] Performance and Scalability
[apply ] Policies and Telemetry
[apply ] Security
[apply ] Test and Release
[apply ] User Experience

**Additional context**

**Comment by ericvn** [comment]
Not sure what this issue is for. Please update and re-open if necessary.
