### ISSUE TITLE
Add targetRef field to Istio CRDs that use workloadSelector

### ISSUE THREAD

**Issue by MorrisLaw** [istio/api#2885]
These tasks can be done in one PR or in multiple PRs. Only caveat is that the targetRef proto definition needs to exist first before being added as a field to the different places we want to update, so we'll need to add that as a first step.

- [ ] Create targetRef proto definition and ~add it to istio/api/gateway. Gateway directory will be a new directory~ [UPDATE] it should be added to istio/api/types. The proto definition should look like what's defined in the gateway api spec for PolicyTargetReference: [GEP-713: Metaresources and Policy Attachment_metaresource_ - Kubernetes Gateway API (k8s.io)](https://gateway-api.sigs.k8s.io/geps/gep-713/#policy-targetref-api)
- [ ] add targetRef field to AuthorizationPolicy CRD [via proto definition](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/security/v1/authorization_policy.proto#L465), add any necessary docs within the proto file
- [ ] add targetRef field to Telemetry CRD [via proto definition](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/telemetry/v1alpha1/telemetry.proto#L247), add any necessary docs within the proto file
- [ ] add targetRef field to WasmPlugin CRD [via proto definition](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/extensions/v1alpha1/wasm.proto#L236), add any necessary docs within the proto file
- [x] ~add targetRef field to ProxyConfig CRD [via proto definition](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/networking/v1beta1/proxy_config.proto#L111), add any necessary docs within the proto file~ **UPDATE:** Decided not to do this, see comment [here](https://github.com/istio/api/pull/2888#discussion_r1291670995).
- [ ] add targetRef field to RequestAuthentication CRD [via proto definition](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/security/v1/request_authentication.proto#L441), add any necessary docs within the proto file

**Note:** Be sure to run [make gen-proto](https://github.com/istio/api/blob/3dbbc82d7a3f1e07e8a9678dc0899ca3c0209997/Makefile.core.mk#L35) locally after a proto update to ensure the necessary protobuf related files are generated. Documentation in the proto is also referenced by some automation in place which will generate docs off of it. Look at some examples like the PR for [jwt.proto](https://github.com/howardjohn/api/commit/bd9c37f95e1df61911b95437510f80d34ebf829f#diff-bc72ea4e8a92ff2fe440685f8cfd2b4e02ea3d3d196a1a318706a3fc1bb2a55b) to see how documentation within the proto can look. Last but not least, be sure to include [release notes](https://github.com/istio/istio/tree/master/releasenotes).

**Comment by howardjohn** [comment]
I would not put it under `gateway` but rather `types`. It is specific to Gateway today but likely not long term.

**Comment by jaellio** [comment]
@howardjohn How do we version `types`? For example, the `WorkloadSelector` is v1beta1, and is referenced in the v1 `AthorizationPolicy`. Thanks!

**Comment by howardjohn** [comment]
It's basically meaningless. Top level types (like AuthorizationPolicy) need to be identical (in yaml) across all versions.

Internal types like workload selector has no relevance for version and probably shouldn't have one at all (but does due to backwards compatible)

**Comment by hzxuzhonghu** [comment]
Wanna to know what target do we need to support?  If i read correctly from other doc, the target is `gateway` for waypoint. 

how could targetref coexist with workload  selector if we need to apply a policy both to a workload and service or someother object

**Comment by MorrisLaw** [comment]
> Wanna to know what target do we need to support? If i read correctly from other doc, the target is `gateway` for waypoint.
> 
> how could targetref coexist with workload selector if we need to apply a policy both to a workload and service or someother object

Hey @hzxuzhonghu, I'm not sure I fully understand both of your questions but I'm going to try. Are you referring to the following lines from the [doc](https://docs.google.com/document/d/1MaMdyIQdOwq7mGCVMYW56FED9HrkJa93Nd0S0zBwws4/edit?usp=sharing)?

> Each resource listed in the Scope section of this proposal will have a new targetRef 
field added to their proto. At present gateway.networking.k8s.io/Gateway is the only valid Kind for this field.

It seems like the main question is "How can targetref coexist with workload selector if we need to also apply policy to a workload and service or other objects"?

The document addresses this I believe:

> In the waypoint, this means binding policies to the waypoint itself. This will be done by introducing a TargetRef field into all workload selector API types, aligning with the "policy attachment" [concept in Gateway API](https://gateway-api.sigs.k8s.io/references/policy-attachment/).

> There are several Istio CRDs that use workloadSelector; however, not all of them are relevant for Ambient. Thus, the scope for this proposed change is limited to the following resources:
AuthorizationPolicy
Telemetry
WasmPlugin
ProxyConfig
RequestAuthentication

> Waypoint proxies will accept label selectors if they match AND there is no targetRef specified

So I think that if NO targetRef is specified, then we'll default to workload selector. BUT if there is a targetRef specified then we'll use that instead. That's how they could co-exist initially. After some number of releases we'll want to switch over to only using targetRef and ignoring label selectors.

cc/ @keithmattix (please fill in any details, or correct me if any of this doesn't make sense)
