### ISSUE TITLE
Promote Telemetry API CRD to Beta

### ISSUE THREAD

**Issue by whitneygriffith** [istio/api#2977]
This issue is a part of [#46720](https://github.com/istio/istio/issues/46720) and covers the implementation details in the istio/api repo for creating a Beta Telemetry API.

[RFC: Istio Telemetry Beta API](https://docs.google.com/document/d/16A-E-30txN5Y2V_9qrDNpVC3lT7P6aa_3Qdg6_4t5Sg/edit)

**Comment by craigbox** [comment]
Is this fixed for 1.22, or are we holding it open for the fields that remain in Alpha?

**Comment by whitneygriffith** [comment]
> Is this fixed for 1.22, or are we holding it open for the fields that remain in Alpha?
This is fixed!
