### ISSUE TITLE
Remove API version tabs

### ISSUE THREAD

**Issue by howardjohn** [istio/api#2994]
https://istio.io/latest/docs/reference/config/networking/destination-rule/ for example.

There is no need for this. 100% of users should use v1beta1. We should pretend v1alpha3 does not exist.

**Comment by bleggett** [comment]
Is there _any scenario where the docs _should_ show multiple versions of the API, rather than just the latest stable?

I guess the only place might be explicit migration guides or alpha/beta features?

+1 on default posture being "don't use them, at all".

**Comment by AndreaM12345** [comment]
looks like this might be the full list of files to adjust:

https://istio.io/latest/docs/reference/config/networking/destination-rule/
https://istio.io/latest/docs/reference/config/networking/workload-group/
https://istio.io/latest/docs/reference/config/networking/gateway/
https://istio.io/latest/docs/reference/config/networking/service-entry/
https://istio.io/latest/docs/reference/config/networking/sidecar/
https://istio.io/latest/docs/reference/config/networking/virtual-service/
https://istio.io/latest/docs/reference/config/networking/workload-entry/
https://istio.io/latest/docs/reference/config/networking/workload-group/

https://istio.io/latest/docs/reference/config/security/request_authentication/
https://istio.io/latest/docs/reference/config/security/authorization-policy/

**Comment by linsun** [comment]
+1 on this. multiple tabs were useful during transition but not needed atm.
