### ISSUE TITLE
Define the structure of istio/api repo

### ISSUE THREAD

**Issue by wora** [istio/api#3]
github.com/googleapis/googleapis has a well defined structure. We should do the same for istio/api repo. For example, we can structure it like:

- istio/mixer/v1
- istio/config/v1
- istio/attribute/v1
- istio/adapter/authentication/v1

When we add more components, it is easy to put them into the right place. We also want a clear versioning story, such as no breaking change within a major version, no dependency between two major versions of the same component, all new features must default to off, how to tag Alpha/Beta/GA of individual features.

When many people contribute to the system, we need more guidelines to scale the development. Such rules are simple to define and relatively easy to follow.

**Comment by douglas-reid** [comment]
I like some of these suggestions. The more I look at it, I don't like having 'api' in the path beyond istio/api.
