### ISSUE TITLE
Define Istio standard attribute vocabulary (yml)

### ISSUE THREAD

**Issue by mandarjog** [istio/api#30]
Define standard attribute vocabulary for istio as a yml file using attribute descriptor format.
https://github.com/istio/api/blob/master/mixer/v1/config/descriptor/attribute_descriptor.proto

Mixer uses a machine readable version of the vocabulary document while evaluating expressions and mapping attributes.

Proxy will produce attributes as described in the document.

**Comment by wora** [comment]
Before we do that, let's move all descriptors to istio.descriptor.v1. They don't belong to mixer.

**Comment by mandarjog** [comment]
That is where it was defined before.
@geeknoid had a reason to move it to mixer. ?

**Comment by geeknoid** [comment]
The attribute descriptor should indeed be moved out of mixer's namespace, it's more general than just the mixer.

But all the other descriptors however are entirely part of the mixer. Only the mixer consumes and processes these.

**Comment by wora** [comment]
In that case, we can put attribute descriptor and attribute vocabulary in a single place. We don't need to touch other things for now.

**Comment by mandarjog** [comment]
https://docs.google.com/spreadsheets/d/1GmoBUkyfBtn8eLNS3rDmU1GScGRES9ziKpXlDKSIAyQ/edit?ts=589cdeb8#gid=0

**Comment by geeknoid** [comment]
We're tracking this in issue #97 in the Istio repo
