### ISSUE TITLE
Update proto comments to conform to protodoc syntax

### ISSUE THREAD

**Issue by ZackButcher** [istio/api#303]
With the plans to open source the docgen tooling that Istio currently uses on ice for the foreseeable future, we need an open source doc generation tool. The best tool at hand is likely `protodoc`, written for Envoy's proto APIs.

We need to update our existing proto comments to conform to `protodoc`'s syntax, and use `protodoc` to generate our documentation from here on out.

**Comment by geeknoid** [comment]
We have the wonderful protoc-gen-doc solution, so we're all set.
