### ISSUE TITLE
Consider defining the ServicePort.protocol as an enum?

### ISSUE THREAD

**Issue by spacewander** [istio/api#3056]
https://github.com/istio/api/blob/a9e8f960650fddcb53f81cab3f2d265e72b2015c/networking/v1beta1/service_entry.proto#L971-L975

Currently, there is a comment claiming that the protocol `MUST BE one of HTTP|HTTPS|GRPC|HTTP2|MONGO|TCP|TLS`. It would be better to define this field as an enum, so it can be checked automatically. The definition can be reused in the code which uses istio API.

**Comment by howardjohn** [comment]
Changing from string to an enum is a breaking change in protobuf so this cannot happen AFAIK, even if it may or may not be a better option
