### ISSUE TITLE
DestinationRule tls settings ambiguity

### ISSUE THREAD

**Issue by frankbu** [istio/api#312]
1) Why is the `mode` field in `TLSSettings` REQUIRED?
  ```
  // REQUIRED: Indicates whether connections to this port should be secured
  // using TLS. The value of this field determines how TLS is enforced.
  TLSmode mode = 1;
  ```
  Since the `TLSSettings` themselves are NOT required, there must be a default mode (DISABLE) when the tls settings are not provided at all.

2) Why even is there a DISABLE value for `mode`? Seems that the only reason one needs to provide a TLSSettings field is to configure tls (SIMPLE or MUTUAL), the other fields in TLSSettings are only applicable for those cases. So, "no tls settings == disable" seems all that's needed.

**Comment by rshriram** [comment]
if TLS is not set, then it is untouched. In this case, if Istio auth is enabled, the tls settings is essentially istio mTLS. But if TLS is set, then it provides a way for the end user to override the Istio mtLS, with their own TLS settings (mtls or simple tls or even disable istio-mtls to a specific destination).

Would it be clear if I made the istio-mtls as a default mode?

**Comment by frankbu** [comment]
That makes sense, probably just would be good to document that Istio mTLS (or simple TLS for external services) is the default and that DISABLED can be used to turn it off for a specific destination.
