### ISSUE TITLE
Update PeerAuth Documentation to indicate that API Dev is frozen

### ISSUE THREAD

**Issue by whitneygriffith** [istio/api#3125]
I think we should update the API docs to indicate that the API is also frozen and likely to be replaced in ambient

_Originally posted by @louiscryan in https://github.com/istio/api/issues/3112#issuecomment-1995142260_

**Comment by whitneygriffith** [comment]
@howardjohn should this just be a comment in both the v1beta1 and v1 resource? How do we set the source of truth for [istio.io](https://istio.io/latest/docs/reference/config/security/peer_authentication/) to be v1?

Also, how do I get the warning box similar to what was done for Istio Operator? https://istio.io/latest/docs/setup/install/operator/

**Comment by howardjohn** [comment]
for istio.io, `$mode: none` is how to opt-out. So the one without that is the source of truth.

warning box is like 

```
{{< warning >}}
blah
{{< /warning >}}
```

**Comment by whitneygriffith** [comment]
@howardjohn I added `$mode: none` to v1beta1 and removed it from v1 but when `make gen` is run it reverses the changes, setting `$mode: none` on v1. Is this because of sync?

**Comment by howardjohn** [comment]
The sync should only apply to lines after the sync-start line, which is after `$mode`
