### ISSUE TITLE
Establish API style guide for Istio

### ISSUE THREAD

**Issue by wora** [istio/api#316]
As we are creating more and more Istio APIs, I think we should establish a formal API style guide for Istio APIs. The same guide can also be used for other companies to build their APIs built on top of the Istio platform.

The reason for having an API style guide is to ensure consistency and minimize friction across APIs, such as `HTTPRequest` vs `HttpRequest`. For certain concepts, such as `country_code` vs `region_code`, it would be impossible for a client to translate data if two APIs use different standards.

Because Istio APIs are using proto3 and gRPC, I recommend we use Google's [API Design Guide](https://cloud.google.com/apis/design) as the baseline. Because it was developed along with proto3 and gRPC, they are naturally very compatible. It has been widely used by hundreds of products over past 4 years, and reaches great stability at this time.

Recently, Envoy community has established its style guide based on Google's API Design Guide, https://github.com/envoyproxy/data-plane-api/blob/master/STYLE.md. I think Istio community can do the same. The consistent developer experience across Envoy, Istio, proto3, gRPC and Google APIs will provide great long term value.

**Comment by douglas-reid** [comment]
@wora have you done an assessment of the current API to see how many violations exist currently if we were to adopt the Google API Design Guide?  How far off are we currently?

Also, can we explicitly state the scope proposed (covering attributes, mixer adapter config protos, etc.)?

Finally, is there an existing API linter that we could use to warn for style issues moving forward?

**Comment by wora** [comment]
Since we only have 27 proto files in this repo, the total amount of changes won't be very significant.

A few common things we need to address are:
-   Directory name and package name must be identical.
-   Strict versioning rule, e.g. the version string must be at the end of package name.
-   Always use camel case for type names, e.g. `HttpRequest`.
-   Follow the best practice for enum values, see https://github.com/envoyproxy/data-plane-api/blob/master/STYLE.md

I know some people prefer to have `istio.mixer.v2.config`, but such scheme doesn't work for `istio.mixer.v2beta2.config`. We should have strict mapping between proto and k8s, e.g.
```
apiVersion: config.istio.io/v1alpha1
kind: Authorization
```
maps to
```
package istio.config.v1alpha1;
message Authorization{}
```
Please enforce the mechanical mapping, so we don't need to debate in the future.

We should cover all proto files in this repo, with additional guidelines agreed by Istio community, much like the Envoy community.

Google API linter is not open sourced, but it is too Google-specific, which won't be suitable for Istio. We can introduce an Istio linter later on. In general, the linter just scan through the proto descriptor and apply the rules. It shouldn't be hard.

**Comment by wora** [comment]
If we look at the mixer v1 api, we can easily change it to use concrete proto and create mixer v2, but there is no need to touch the template and config stuff. By putting v1 in the middle of package, we force everything to be upgraded at once. That is not feasible for any real product. By forcing the version to be the last segment of package, we can update each package individually. That is the reason we designed the versioning scheme this way.

At Google, we manage thousands of API versions using this versioning strategy across many large products, and it works really. I suggest we follow the same strategy for Istio.

**Comment by xiaolanz** [comment]
@geeknoid and I have chatted about this. For config APIs, the plan is to following through k8s API style guide  and the additional rules with google api style.

I have the plan to go through all config API shortly so I will fix any violations along the way.
I will also working on to setup linter for Istio protos.

I don't have much bandwidth for non-config API now. I wonder somebody can volunteer?

**Comment by wora** [comment]
We don't have many proto files in this repo. Even we leave some of them out for compliance, it is still better to have a guideline for all future APIs.

**Comment by wora** [comment]
This issue is fixed.
