### ISSUE TITLE
Change ClusterId to a string, use as opaque config reference.

### ISSUE THREAD

**Issue by smawson** [istio/api#32]
In the proxy config we currently have a ClusterId which is a complex type, and is expected to match exactly in multiple places in the config. This seems onerous, and instead we should have a simple string that is used for matching between multiple places in the config, and leave the tags part to the UpstreamCluster definition.

For example:

message UpstreamCluster {
  string cluster_id = 1;
  repeated string tags = 2;

  string health_check_endpoint = 3;
  ...
}

message WeightedCluster {
  // Must match a cluster_id from an UpstreamCluster definition.
  string dst_cluster = 1;
  uint32 weight = 2;
}

**Comment by wora** [comment]
In the code review, I suggest we should use URI/URL to refer a cluster.

**Comment by kyessenov** [comment]
https://github.com/istio/manager/pull/105 eliminates "upstream cluster" with destinations and (opaque) service versions.
