### ISSUE TITLE
Rename UpstreamCluster to something that doesn't include "Cluster"

### ISSUE THREAD

**Issue by smawson** [istio/api#33]
Some ideas:
- Destination
- Upstream
- Target
- Server

The word "cluster" has a very different meaning in kubernetes (and elsewhere) than what it is being used for here, which is overly confusing.

Other name suggestions welcome.

**Comment by wora** [comment]
I had the same comment in the code review. Cluster is too specific and unnecessary.

**Comment by kyessenov** [comment]
https://github.com/istio/manager/pull/105, destination it is.
