### ISSUE TITLE
ca_certificate in destination_rule

### ISSUE THREAD

**Issue by costinm** [istio/api#331]
The comment on the ca_certificate:

 "If omitted, the proxy will not verify the server's certificate." 

That's really bad for outbound traffic (and for pretty much everything else).
 
Should be:

"If omitted, the proxy will verify the server certificate using existing root CAs".

If we want to also allow 'insecure' mode (no verification) - we can add a separate flag, 
but it can't be default.

Also not sure about 'subject_alt_names' - for external traffic it could also match the 
common name, which is most commonly used ( but I guess it's implicit ).
It would be worth clarifying the syntax for san - I assume for external traffic we will 
want to allow domain SANs, but internal (and some external) SANs may be URL type.

**Comment by rshriram** [comment]
So the current behavior is in line with what Envoy does. But I am not opposed to what you are proposing, as long as we figure out a way to reliably ship root ca bundle, and keep that stuff updated over the lifetime of an istio installation.
