### ISSUE TITLE
Retry Budgeting / Deadline propagation

### ISSUE THREAD

**Issue by smawson** [istio/api#34]
Our ProxyConfig is currently point-to-point, meaning that we specify things in terms of timeouts and retries. In order to make this not lead to cascading failures, we need to support deadline propagation (and maybe retry budgets?).

I think the existing user controls make sense:
- Users can specify a per-attempt timeout for routes.
- Users can specify the number of attempts to make for each route.

The system will then support propagating deadlines as follows:

Client Proxy:
No existing deadline:
for # retry attempts:
  Inject per-attempt timeout as timeout header

Existing deadline:
Read timeout from request (TBD headers etc. to use), calculate deadline = current time + timeout
for # retry attempts:
  next_timeout = min(deadline - current time, per-attempt timeout)
  if next_timeout <= 0, abort request.
  Inject next_timeout as timeout header

We'll also need to support deadline propagation in a standard way as part of a broader context propagation story, which we still need to figure out (for starters we can just use grpc context propagation).

Retry budgeting is harder, the best way to do this is with load budgets rather than retry budgets. But I think doing this generically is a non-trivial task, so we're best punting on that for now I think.

**Comment by christian-posta** [comment]
Curious what happend to this enhancement? Seems like a reasonable thing to do. Is it not slotted for any release?

**Comment by smawson** [comment]
I think this fell into a pit, biggest problem is the context propagation issue and I don't think we've resolved that.

**Comment by geeknoid** [comment]
Obsolete

**Comment by raindev** [comment]
@geeknoid was the idea superseded or dropped altogether?
