### ISSUE TITLE
Fault injection not implementable

### ISSUE THREAD

**Issue by kyessenov** [istio/api#388]
Current spec allows faults to be applied per `HTTPRoute`.

Unfortunately, Envoy only allows one fault filter per upstream cluster. That means if you have two HTTP route rules for the same cluster, they'll be affecting each other.

Suggestion is to either:
1) modify route rule spec to align with envoy
2) modify envoy to allow faults per individual routes

**Comment by costinm** [comment]
I don't know about 'not implementable' - we could generate an extra cluster for the route that has a fault filter. 

However the implementation may be too expensive or complicated -  so maybe we should change the API to keep fault at cluster level.

**Comment by kyessenov** [comment]
That's a very wasteful solution on a self imposed problem :)

**Comment by costinm** [comment]
If we believe users need to set fault injection at route level - I wouldn't
say it's
self imposed problem. However - we already provide the means for the user
to achieve this ( by defining his own cluster with fault ) - so maybe we
don't need
the extra complexity.

**Comment by louiscryan** [comment]
I would be fine with moving HTTPFaultInjection into DestinationRule.TrafficPolicy

**Comment by kyessenov** [comment]
@rshriram if you have time, what do you think? Should we fix envoy's fault injection or fix istio's API?

**Comment by mandarjog** [comment]
the current fault injection filter should accept per route configuration.
We are moving all our filters to support that anyway. Mixerclient filter / envoy rbac filter etc...

**Comment by kyessenov** [comment]
After talking to @rshriram , we'll park implementing v1alpha2 fault until it's corrected in envoy to apply config per route, not per upstream cluster. Upstream cluster granularity is too coarse for faults, and it does not match CDS-semantics in Envoy.

**Comment by rshriram** [comment]
Thinking more about this, fault filter cna filter based on HTTP headers and upstream clusters. So, why is this an issue? If two routes refer to same upstream cluster, then logically they should have some difference (header or prefix match). And these conditions can be added to the fault filter.
Keep in mind that filters in envoy can be stacked. You can have N fault filters, with different match conditions.. Only those that match will be triggered.

**Comment by rshriram** [comment]
refer to #405

**Comment by kyessenov** [comment]
I think they are still not implementable. Please reference the envoy fix here when you close it.

**Comment by rshriram** [comment]
https://github.com/envoyproxy/envoy/pull/3084
