### ISSUE TITLE
source_labels is not an HTTP property

### ISSUE THREAD

**Issue by kyessenov** [istio/api#389]
For some reason, source label selector is in HTTP match condition: https://github.com/istio/api/blob/master/routing/v1alpha2/route_rule.proto#L494

Does this mean source labels only apply to HTTP traffic? Why are source workload labels coupled with HTTP?

This does not align well with Envoy xDS since the selector is referencing things that are not properties of the traffic.

**Comment by louiscryan** [comment]
source_labels will be in all XXX_Match types, its there for L4 too. This selector is not applied to traffic but rather it controls whether Pilot will include this rule or not when serving config to a pod (workload) with a set of labels.

**Comment by kyessenov** [comment]
Ok, it feels like source_labels should be pulled up one level above L4/L7 match conditions, but it's not a big difference.

**Comment by mandarjog** [comment]
The same can be said about inclusion of gateway in the match condition.

Workload and traffic match conditions are specified in a uniform way.

**Comment by kyessenov** [comment]
Correct. It seems it would help to have a common message for those deployment-specific conditions.

**Comment by geeknoid** [comment]
Is this issue still relevant?
