### ISSUE TITLE
Update Mixer API to support returning attributes with responses

### ISSUE THREAD

**Issue by ZackButcher** [istio/api#39]
The Mixer API surface needs to be updated to support propagating attributes back to the caller alongside its usual response. One key use case for this is propagating trace information back and forth between the Mixer and Proxy.

**Comment by kyessenov** [comment]
Who generates trace IDs? Can we reuse `x-request-id` and pass it around as a regular HTTP header?

**Comment by ZackButcher** [comment]
AFAIK trace ID generation is left up to the tracer implementation, we don't get to pick it. I originally tried to use gRPC's existing metadata system (which is communicated between client and server via HTTP headers) as the propagation mechanism but gRPC does not and will not support setting custom headers on individual messages in a stream, so that's a dead end for us.

**Comment by kyessenov** [comment]
I see, so x-request-id is some sort of stream-id in GRPC world. Then it makes sense to have a separate request ID for GRPC.

**Comment by wora** [comment]
Because the trace must start at proxy, proxy must generate the trace id, not mixer.

We had poor experience with trace id, operation id, request id, etc. Let's decide a single id across all system. The id should be unique within a time window for a service, such as one day. If we want to make it truly unique, it may be too expensive.

**Comment by ZackButcher** [comment]
It is not true in general that the proxy originates a trace, a request could come in from another caller that includes trace information that we can propagate through our system. For example, suppose I want a trace across all of the services I own. I create a span before I initiate a call to my istio-enabled service, the metadata for that span should be used by the istio components so that I'm able to trace the full execution and I don't have two separate traces, one for istio-pieces and one for non-istio pieces.

It is up to the tracing system to generate the trace IDs, we cannot pick the ID unless we choose to implement our own tracing API. The whole point of us using opentracing is that a user can plug in whatever tracing system they'd like to use (that's compliant with the opentracing API). From our perspective the information we need to send to propagate trace information is a black box.

**Comment by wora** [comment]
When you send a request to a proxy, if the request already has a trace id, the proxy can take it. I would say the decision should be made by proxy, not by mixer. The proxy can choose whatever it likes to generate the trace id, including using an existing one.
