### ISSUE TITLE
Impossible to specify route rule for a kubernetes service by name.namespace

### ISSUE THREAD

**Issue by kyessenov** [istio/api#390]
v1alpha2 route rules only allow short names (e.g. `reviews`). These names are context-dependent, since it needs the namespace of the proxy node to resolve the service name. That means it's not possible to write a config for a fixed k8s service name.

**Comment by kyessenov** [comment]
I think more importantly, this semantics creates a situation that a single istio route rule maps to N * envoy routes where N is the number of namespaces. For each namespace, the istio route means a different thing, so there's no possibility to speed up computation by sharing the envoy routes.

**Comment by costinm** [comment]
Not sure what you mean - which field are you talking about ? destination can be fqdn, hosts can be fqdn.

**Comment by kyessenov** [comment]
Fixed the title.

@costinm how do I write a rule that injects a timeout between `reviews.bookinfo` and `ratings.bookinfo` and only those? I'd like to avoid use domain suffix as that's not portable between clusters.
