### ISSUE TITLE
DestinationRule misses field for the actual name

### ISSUE THREAD

**Issue by andraxylia** [istio/api#421]
DestinationRule proto def has a field called "name" which corresponds to the actual service name spec.name (= "echosrv" in the example below). It misses a field for the metadata.name. This can cause conflicts if 2 destination rules with different names are defined for the same service.

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-echosrv
spec:
  name: echosrv
  subsets:
    - name: subset-v1
      labels:
        version: v1
    - name: subset-v2
      labels:
        version: v2

**Comment by kyessenov** [comment]
Yes, it's known, and not much can be done about it, except running a dynamic validator on top of CRDs.

**Comment by andraxylia** [comment]
We need to use "name" to mean the actual destination rule name, and some other "name" for the service name. This can be done.

**Comment by louiscryan** [comment]
@andraxylia Agree we should rename, would better align with VirtualService too.

This should switch to 'host' just like we changed for VirtualService.  It has literally the same specification as the 'host' field there. Also I think we can make the host field plural in DestinationRule too so we don't have to have redundant duplication of across many hosts.

@rshriram Can you pick this up?

**Comment by kyessenov** [comment]
The issue is "2 destination rules with different names are defined for the same service." The change is that in v1alpha1, the name/namespace of the rule would match the service name/namespace, and that ensured uniqueness. Since this is no longer the case, we cannot multiple rules pointing to the same service/host, and that can only be stopped by invalidating all but one.

**Comment by andraxylia** [comment]
If there is only one Destination Rule allowed for a service, then we do not need two names. The name of the service should be used as the name for the k8s resource. This will ensure uniqueness, and there is no need for extra validation in istioctl.

**Comment by rshriram** [comment]
resolved
