### ISSUE TITLE
DestinationRule: TLS policy for different ports

### ISSUE THREAD

**Issue by costinm** [istio/api#449]
If service foo has multiple ports, some may have their own (M)TLS in app space, some may be clear text and some may want to have Istio MTLS added. 

Right now I don't think this can be expressed in the API - except by making some decisions based on the port name ( which I don't think we do in the implementation ).

**Comment by rshriram** [comment]
its a TODO. I even had a PR opened for this a while ago and then closed it as I didn't have time to get to it.. let me dig it up and reopen the PR

**Comment by rshriram** [comment]
solved by #450
