### ISSUE TITLE
Add ability to generate headers from templates via routing rules

### ISSUE THREAD

**Issue by Adiqq** [istio/api#454]
Hi,

Opening new issue according to suggestion from @rshriram , https://github.com/istio/istio/issues/4971 .

Edit:
This issue is not about automatic header propagation through inference. This issue is about generating headers based on templates, nginx style
e.g.,
set-header proxy-pass $proxy_ip
this should cause the proxy to generate a header called proxy-pass whose value is the IP address of the proxy. Several proxies support this kind of feature except Envoy [or may be it does it by now in a limited way].

**Comment by rshriram** [comment]
cc @frankbu (if you have time to help)

**Comment by geeknoid** [comment]
Note that we're also planning to support this kind of functionality through Mixer policies.

**Comment by ijsnellf** [comment]
@geeknoid: is the mixer work being tracked somewhere?

**Comment by kyessenov** [comment]
@ijsnellf I'm driving the effort. All the bits are in place, but not connected end-to-end. Mixer rules will allow using expressions for header values, which can depend on request attributes or any other input from the adapters.

**Comment by linsun** [comment]
subscribe

Curious why we want to do this via mixer rule.... This is not just for telemetry.  I'd think I want to do header based routing without mixer even installed.

**Comment by geeknoid** [comment]
We want Mixer adapters to be able to influence routing decisions. This
makes it possible for Mixer to reach out to a database which supplies the
routing info for a specific customer (which happens in API management
scenarios, among others)

**Comment by kyessenov** [comment]
@linsun We don't want to do this _just_ with mixer rules. For simple things, route rules work fine. You need Mixer for any external adapters trying to influence request metadata. Anything that involves an external database would need dynamic rules.

**Comment by linsun** [comment]
@kyessenov @geeknoid ok great.  So if I hear you correctly, this will enable users to propagate headers (such as user-agent) automatically among microservices without the need to modify their code.  Further, you could do this in the minimal istio install without mixer (https://istio.io/docs/setup/kubernetes/minimal-install/) for route rules... when you bring in mixer, there is added capability such as make decisions/modify based on request metadata.  

Is there a design for this?  I would like to follow up this closely.   Curious how you propagate the headers for the user without mixer for incoming req and outgoing req.

cc @frankbu

**Comment by kyessenov** [comment]
@linsun Let me clarify. Mixer-driven header operations are not meant for automatic header propagation. It's meant for building higher-level workflows with adapters and istio config. For example, a mixer authorization adapter may insert `user-info` header that also affects how envoys route traffic (by redirecting requests without user-info to a login page). The design has been in discussion for many months, see https://docs.google.com/document/d/1-coh6cK4Tk0_Yw1Vv1JxBUs2aP5miaqo4zCPSFgLiaA/edit#heading=h.qex63c29z2to, for example. I will provide more documentation likely next week.

**Comment by linsun** [comment]
@kyessenov thank you for clarifying that!

**Comment by andrew-dinunzio** [comment]
Came here looking for automatic header propagation.. @linsun did you say this is possible using only route rules? Or will solving this issue make this possible using only route rules?

**Comment by frankbu** [comment]
@kyessenov, please correct me if I'm wrong, but I think the Mixer support is working now.

@linsun, @adinunzio84, there is no plan to support automatic header propagation in route rules or Mixer. A general automatic solution to correlate incoming and outgoing requests, without application involvement, is not realistic.

Given the Mixer solution, I think we should close this issue now.

**Comment by linsun** [comment]
@frankbu Agreed, no plan for auto header propagation at the moment.

**Comment by rshriram** [comment]
Just to clarify, this issue is not about automatic header propagation through inference. This issue is about generating headers based on templates, nginx style
e.g.,
 `set-header proxy-pass $proxy_ip`
this should cause the proxy to generate a header called `proxy-pass` whose value is the IP address of the proxy. Several proxies support this kind of feature except Envoy [or may be it does it by now in a limited way].

**Comment by howardjohn** [comment]
I believe this is possible now via https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers
