### ISSUE TITLE
Bad comment in mixer/adapter/model/v1beta1/extensions.proto

### ISSUE THREAD

**Issue by douglas-reid** [istio/api#482]
See: https://github.com/istio/api/blob/7e10af28c89ef66637dbad64fdd324c652263667/mixer/adapter/model/v1beta1/extensions.proto#L32

Comment needs to reflect attribute generation, rather than quota.

**Comment by guptasu** [comment]
Bundled this into pr https://github.com/istio/api/pull/481#pullrequestreview-119988981
