### ISSUE TITLE
Move the Dockerfile and build image scripts to istio/istio

### ISSUE THREAD

**Issue by douglas-reid** [istio/api#489]
This would allow building of the build image to pull files from istio/istio's vendor directory, and help to ensure that istio/api generated files still compile into istio/istio appropriately.

Also, we could provide formal support for the mgmt of the build image, especially as it is being updated.

cc: @ldemailly , @hklai

**Comment by geeknoid** [comment]
We want to move all of istio/api into istio/api, so maybe we don't need to do this separately?

@rshriram You feel like moving istio/api over soon?

**Comment by ibm-jason** [comment]
@rshriram are you still working on this? Is this still needed?

**Comment by costinm** [comment]
I believe last decision was to keep separate repos and components. We
should close this.

**Comment by ibm-jason** [comment]
@costinm thanks for the info. I'll go ahead and close.
