### ISSUE TITLE
Update mixer descriptor protos to be consistent

### ISSUE THREAD

**Issue by ZackButcher** [istio/api#49]
We have a mix of descriptors that reflect our current thinking when they were created. As a result, we have a slew of different styles. We've settled on the style used by the [MetricDescriptor](https://github.com/istio/api/blob/master/mixer/v1/config/descriptor/metric_descriptor.proto) (the QuotaDescriptor standardized on this), the rest of the descriptors need to be brought up to date.

**Comment by wora** [comment]
Any explanation about the difference between attribute descriptor and label descriptor?

**Comment by ZackButcher** [comment]
They are very similar structurally, but have different semantics: labels dimension other things in the systems (metrics, quotas, logs, etc), while attributes describe values the system knows about at runtime. If labels used the `AttributeDescriptor` message too then it'd be too easy for users to make the mistake of thinking that a label can only be a single attribute, rather than an entire expression. Further, they're used close to each other: both attributes and labels will be present in a user's config, and attributes are used in expressions that produce values for labels. Because of this, we thought it'd be simpler conceptually to split the two concepts.

@geeknoid your thoughts here?

**Comment by geeknoid** [comment]
I think you captured it succinctly. Attributes and labels live in different namespaces and serve different purposes.

Attributes provide metadata about an individual request and the environment in which it runs in. We use attributes to apply policies. Labels on the other hand are output state from config evaluation, representing inputs to our adapters.
