### ISSUE TITLE
Future of quota spec binding

### ISSUE THREAD

**Issue by kyessenov** [istio/api#509]
Quota spec binding is used to bind mixer quota resource name to a proxy. It's done through an intermediary called `IstioService` (see https://github.com/istio/api/blob/14a33dbe9d2d387b06dbf2da68bb22581c0f20f4/mixer/v1/config/client/quota.proto#L126). We should re-consider how quotas are selected at the server-side sidecar in light of the deprecation of IstioService and v1alpha1 APIs.

cc @geeknoid @ayj @louiscryan

**Comment by ayj** [comment]
[HTTPAPISpecBinding](https://github.com/istio/api/blob/14a33dbe9d2d387b06dbf2da68bb22581c0f20f4/mixer/v1/config/client/api_spec.proto#L223) also needs to be addressed.

What's the alternative to binding to (one of) the service's network addressable name (i.e. host:port)? I would say the canonical service name, which would cover cases where a service is addressable through different network names (e.g. ?), but I'm not sure what a user would specify that is different from the network name. 

Subsets might also be useful for things like disabling quota on canary versions or changing an API method on a new version being rolled out. This is similar to authentication policy's [TargetSelector](https://github.com/istio/api/blob/e01d1410438cb9003b02252a1aad0b718a0f2811/authentication/v1alpha1/policy.proto#L312)?

**Comment by gyliu513** [comment]
I think we can not continue use `Quota` in istio, as it confilict with Kubernetes `Quota`, please refer to https://github.com/istio/istio/issues/5532 for detail.

**Comment by kyessenov** [comment]
@rshriram since you asked me offline ^^^

**Comment by vadimeisenbergibm** [comment]
@kyessenov @rshriram any updates on that issue? Can I define a quota for a ServiceEntry? See this question - https://stackoverflow.com/questions/53931913/how-to-enable-rate-limits-for-outside-urls-in-istio

**Comment by kyessenov** [comment]
cc @gargnupur

**Comment by skydoctor** [comment]
@geeknoid @mandarjog @kyessenov I think this still needs work. Can we remove the lifecycle/to-be-closed tag?
