### ISSUE TITLE
RBAC proto uses improper style for roleRef

### ISSUE THREAD

**Issue by jeffmendoza** [istio/api#686]
```
rbac/v1alpha1/rbac.proto:162:3:Field name "roleRef" must be lower_snake_case.
```

Please fix if possible and remove lint exception below. Thanks.

https://github.com/istio/api/blob/master/prototool.yaml#L9

**Comment by jeffmendoza** [comment]
cc @liminw 
Do you know if this shipped in Istio already?

**Comment by liminw** [comment]
Yes. This field was introduced in Istio since 0.5 release. If we want to fix it, we have to deprecate the existing field and introduce a new field.

**Comment by jeffmendoza** [comment]
I was looking through where this is referenced. It looks like this is used in yaml for CRDs. Yaml normally accepts the camelCase when the proto is lower_snake. I think we can change this to role_ref without breaking the yaml. Thoguhts?

**Comment by ozevren** [comment]
I believe it should be possible to rename the field without creating a new
one. both roleRef an role_ref in proto should map to "roleRef" in Yaml. In
the Proto, renames do not have an affect. So this should be a
straightforward non-breaking change.

It is still safer to do this post-1.1 though probably.

**Comment by yangminzhu** [comment]
@ozevren Thanks for the note, I'll try to rename and have a test.

**Comment by yangminzhu** [comment]
Closing this one as we'll have the v2 API soon.
