### ISSUE TITLE
API Document

### ISSUE THREAD

**Issue by clyang82** [istio/api#722]
Do we have an OpenApi 2.0 / Swagger API document for `istio/api`? if so, please tell me where can i find it? Thanks.

**Comment by ayj** [comment]
cc @ozevren @jeffmendoza

**Comment by ozevren** [comment]
Hi, we don't have a Swagger doc for the API, but I've started a somewhat related work for having some tooling that can generate OpenAPI spec for our CRDs for validation purposes. The prototype is here: https://github.com/istio/tools/pull/30

This is obviously not complete, but can be used to generate an Open API  document as well.

**Comment by ozevren** [comment]
What's your use case?

**Comment by clyang82** [comment]
@ozevren Thanks for your response. Glad to know you are working on generating OpenAPI spec. I do not have the special use cases. Just normal case to check the API document for reference.

**Comment by linsun** [comment]
Agreed this would be good to have and it is easier than reading out proto file directly from the api repo today.

**Comment by ozevren** [comment]
FWIV, if you're just looking for reference, https://istio.io/docs/reference/config/ is the right place. Most of the content here should be getting auto-generated. There is also hand-written sections here and there as well.

**Comment by jasonwzm** [comment]
@clyang82 openapi schemas are added in api repo along with the generated files. The schemas will be published to k8s once we have those in our CRDs if the user has [1.14+](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2).

**Comment by jasonwzm** [comment]
Any other use cases you are looking for?

**Comment by clyang82** [comment]
Let me just close this issue. we can open it once we have other user cases.
