### ISSUE TITLE
Sidecar Injection using API/Automation

### ISSUE THREAD

**Issue by salmanbukhari** [istio/api#749]
I am automating Istio sidecar deployment. I want to inject the Istio Sidecar in the Kubernetes Pod created using kubernetes-client-go.  Is there a way to inject the sidecar using API? Is there a way to inject ISTIO sidecar without configuring webhook to the namespace?

**Comment by hzxuzhonghu** [comment]
We also provide `istioctl kube-inject` .

**Comment by salmanbukhari** [comment]
@hzxuzhonghu  , I know about the command. I want to ask, is there any API for doing that? Like where I can give the file or even do it in memory and it will inject the sidecar?

**Comment by hzxuzhonghu** [comment]
I think no.  All you need is the injector logic currently sidecar-injector does.
