### ISSUE TITLE
Converting API Objects to YAML

### ISSUE THREAD

**Issue by salmanbukhari** [istio/api#775]
Is there a parser/decode function from which we can populate and convert the API objects for example v1alpha3.VirtualService to YAML? All the objects defined in API contains attributes defined in "spec". I need to convert these to YAML file which can be executed using kube-ctl.

**Comment by ozevren** [comment]
Can you give more details? It looks like with that approach, you won't have access to the metadata. If you only have the raw proto (which means you don't have the metadata), then your best bet is to serialize proto => JSON => YAML, use it as the spec field, and fill out the rest of the metadata yourself (from a separate source).

**Comment by ozevren** [comment]
I am closing this. Feel free to use the discuss groups to ask product related questions.
