### ISSUE TITLE
"uri" defined in HTTPMatchRequest&HTTPRedirect is path rather than uri

### ISSUE THREAD

**Issue by idouba** [istio/api#837]
A standard [uri ](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)should look like this: URI = scheme:[//authority]path[?query][#fragment].
And the uri referenced in VirtualService, such as HTTPMatchRequest, HTTPRedirect  is simply a path. The field _uri_ seems be a little confusing, maybe path can be better understood.

**Comment by rshriram** [comment]
@frankbu what do you think of this? I too think that the path is a better term for uri.

**Comment by frankbu** [comment]
Do I think `path` would be a better field name than `uri`? Maybe.

Do I think it's worth deprecating the old field and creating a new one? Probably not.
We would also need to change the `ignoreUriCase` field to `ignorePathCase` to be consistent.

I think maybe we should instead update the documentation to clearly say that it's the path part of the uri that the field is matching.

**Comment by howardjohn** [comment]
While I think this is technically correct, the cost to fix it outweighs the benefit so I think we are stuck with the current state. Note Gateway API HTTPRoute did not make the same mistake
