### ISSUE TITLE
Invalid RBAC example in rbac/v1alpha1/rbac.proto

### ISSUE THREAD

**Issue by esnible** [istio/api#850]
RBAC example in _rbac/v1alpha1/rbac.proto_ includes

```
//     constraints:
//     - key: "destination.labels[version]"
//       value: ["v1", "v2"]
```

That's not right; it should be `values` not `value.

See also https://github.com/istio/api/issues/847

**Comment by esnible** [comment]
@geeknoid When I validate the RbacConfig `istio-system` in _rbac.proto_ the message is

```
2019-03-12T13:14:38.345265Z	warn	model	RbacConfig is deprecated, use ClusterRbacConfig instead.
```

Two questions.  First, should we be giving examples of things we have deprecated?

Second, this message showed up via logging and not through the usual `istioctl validate` message.  This is because it is a warning, not a validation.  Should I create an Issue in istio/istio to figure out how to handle such warnings?

**Comment by geeknoid** [comment]
We definitely shouldn't be giving examples of things we have deprecated, that's worth fixing.

And yes, we need to be more proactive about deprecation. Folks can easily miss a log message and then will be surprised during the next upgrade cycle when features they still depend on get deleted.
