### ISSUE TITLE
Sidecar proto and egress namespace special characters '.' and '~'

### ISSUE THREAD

**Issue by esnible** [istio/api#878]
_sidecar.proto_ says "The `namespace` can also be set to `*` to select a particular service from any available namespace".

https://github.com/istio/istio/blob/master/pilot/pkg/model/validation.go#L650 says the namespace can be *, or ., or ~.

We should either document the '.' and '~' cases as official or note that they are experimental.

**Comment by hzxuzhonghu** [comment]
"." current namespace has been supported. But looked through the code, haven't found "~"   supported.

**Comment by frankbu** [comment]
It looks like both the `Sidecar` and `Gateway` doc needs to be updated to describe the behavior of "*" and "." namespace values. They are both implemented in the code, but not documented thoroughly.

Like @hzxuzhonghu I can't find anything in the code that handles namespace "~", so we should either implement it or remove it from the validation check. What is it intended to represent? The namespace of the pod using the sidecar? Is it supposed to be allowed for gateways and sidecars, or just sidecars?

@rshriram Do you know what's intended here?

**Comment by rshriram** [comment]
lol. I thought I had documented this. So `~/~` is supposed to imply "import nothing" in a sidecar. This is useful for sidecars that simply receive traffic and respond to, but make no outbound connections on their own.
