### ISSUE TITLE
Virtual Service Deserialization 

### ISSUE THREAD

**Issue by ivelichkovich** [istio/api#890]
So I'm using a wrapper around the kubernetes client to programmatically access istio resources. 

I have this chunk of code just requesting for virtualservice and trying to transform it into the virtualservice struct

`	result = &v1alpha3.VirtualService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)`

It works for the most part but the virtualservice is missing some fields, they're all protobuf_oneof fields as far as I can tell.

for example with this virtualservice 
`spec:
  hosts:
  - details
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percent: 100
    route:
    - destination:
        host: details
        subset: v1
      weight: 63
    - destination:
        host: details
        subset: v2
      weight: 37`

I'm getting this result 
`spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: v1
          weight: 63
        - destination:
            host: details
            subset: v2
          weight: 37
      fault:
        delay:
          percent: 100
          HttpDelayType: null`

Is this just a versioning issue or am I doing something wrong? I'm running istio-1.0.6 on my cluster and using release-1.0 in my code so I doubt the virtualservice protobuf stuff changed between those but it's possible. 

Any help would be greatly appreciated though.

**Comment by ozevren** [comment]
Hi, this issue seems to be a bit old. Are you still running into this problem? How is the wrapper library implemented?
