### ISSUE TITLE
Consider merging EnvoyFilter into Gateway and Sidecar APIs

### ISSUE THREAD

**Issue by rshriram** [istio/api#900]
@costinm suggested this..

There are pros and cons to this approach.
EnvoyFilter allows programming proxies across various namespaces, with one single config. Like adding a special IAM filter for all proxies in the system. Or same argument could be made for specific settings like idle timeouts for all clusters in the system..

If we move this functionality to a sidecar or Gateway CRD, we would have to replicate this for every namespace or gateway. Sidecars in config root namespace will not work as we don't support inheritance.

So how do we balance both?
@louiscryan

**Comment by costinm** [comment]
All global settings are dangerous  - upgrades, config changes, isolation
are affected.
They assume all sidecares are the same.
We do have a way to specify defaults - and we discussed having overrides or
other merging semantics.

But we can keep them - my point was mainly about adding equivalent
functionality to sidecar and gateway so they can be used consistently.

**Comment by rshriram** [comment]
closing for now as envoyfilter has become its own beast;
