### ISSUE TITLE
Method Not Allowed for pilot istio post api

### ISSUE THREAD

**Issue by monubamb** [istio/api#913]
Trying to add a new SE into pilot.. i get method not allowed. Is this api not supported?

kubectl run -i --rm --restart=Never dummy --image=curl:alpine \
> -n istio-system --command \
> -- curl -d '{"service-key": "172.16.0.8|http","hosts": [{"ip_address": "172.16.0.8","port": 6009}]}' -H "Content-Type: application/json" -X POST **http://istio-pilot.istio-system:8080/v1/registration**

**Comment by geeknoid** [comment]
Hi,

Sorry for the delay in responding. Please post questions in our discussion forum at https://discuss.istio.io. There are plenty of folks there to help.

Thanks.
