### ISSUE TITLE
MCP resource name format is actually "namespace/name"

### ISSUE THREAD

**Issue by jeffmendoza** [istio/api#939]
https://github.com/istio/api/blob/master/mcp/v1alpha1/metadata.proto#L55

    //    "/<k8s namespace>/<k8s resource name>"

This is incorrect, we are seeing "namespace/name" (without leading slash) on live data. Seems like the Galley code is good and working, so the right thing to do is update the comment/docs.

**Comment by jeffmendoza** [comment]
cc @panywei @qfel @ozevren

**Comment by kaushikchaubal** [comment]
I can pick up this issue and create a PR. This is going to be my first PR to this community so if anything is incorrect, please shout out.

**Comment by jeffmendoza** [comment]
Sounds good. Make sure to follow https://github.com/istio/api#updating to update the generated files.

**Comment by kaushikchaubal** [comment]
I have created a PR here: https://github.com/istio/api/pull/944. Looks like it is awaiting a trusted user to review the PR and leave an /ok-to-test message.

**Comment by kaushikchaubal** [comment]
this is now merged. Should i close this issue now?
