### ISSUE TITLE
Add Null Type to Mixer ValueTypes

### ISSUE THREAD

**Issue by mandarjog** [istio/api#98]
Most other attribute processing frameworks have a notion of NULL type. We do not have this in Istio. 

This will bring Istio attributes inline with other internal efforts.

**Comment by geeknoid** [comment]
We should consider this in the broader context of CEL and how we handle nil/null values in general.

**Comment by wora** [comment]
Do we still consider to use CEL since it is open sourced now?

**Comment by geeknoid** [comment]
Yes, Oz is tracking CEL evolution for us and we hope to converge.

**Comment by kyessenov** [comment]
https://github.com/google/cel-spec/blob/master/doc/langdef.md is the spec for reference.
I immediately noticed that the last change about short-circuiting && and || violates the spec.

**Comment by ozevren** [comment]
Not sure what you mean by that?

**Comment by ozevren** [comment]
Ah, you mean the commutative property, I presume.

**Comment by kyessenov** [comment]
Yes, `1/0 || true` should evaluate to `true`.

**Comment by ozevren** [comment]
Also I assume you mean my latest PR as violation of this?

If so, yes, that is the case. The current state of the expression language
has some known gaps with CEL. That PR was mainly to fix an issue with the
current expected behavior of the expression language, and was not about
aligning with CEL. Aligning with CEL will require breaking changes compared
to the current expression language behavior. That is a separate, large
chunk of work.

**Comment by kyessenov** [comment]
Right, I was just observing the differences. Doing a breaking language change is going to be difficult after 1.0. Maybe we should drive the language in the right direction gradually (by changing expectations).

**Comment by ozevren** [comment]
Right. That is what I started working on initially,, and have a Go based
CEL parser & type-checker implementation waiting to go to the open-source
world, with the idea that we can start with changing the parser front-end
first (which would have given us some goodies such as ternary expressions).

Unfortunately, that was placed onto the back-burner as we started doing
more productionization work and as some of the CEL semantics was also still
being solidifed. Still, I was able to sneak in some regular expression
methods that aligns well with CEL:
https://istio.io/docs/reference/config/mixer/expression-language.html.
Hopefully, we'll be able to refocus on this soon.If you have any particular
low-hanging fruits in mind that you think can be helpful, I'd be happy to
discuss and see if I can sneak them in as well.

**Comment by kyessenov** [comment]
I would love to get error semantics be aligned. I think the surface syntax change is not as hard on users as semantics change, and probably can be automated. We should use errors for missing fields and missing keys like in CEL, and also use JS-like `e.f == e["f"]` permutation.

Another useful thing is to introduce map and array literals, so that later, we can use data imports into policies.

**Comment by wora** [comment]
If we can consider breaking change, we need decide whether each attribute
behaves like proto2 field or proto3 field. Eliminating null checks reduce
the boilerplate code.

**Comment by ozevren** [comment]
*I would love to get error semantics be aligned.*
That would be a breaking change. Removing our current missing field support
will probably be problematic as we can't support the has() macro yet (and
ternaries). Without those, or safe-traversal primitives, we can't rewrite
some of the existing expressions. Other things like array/map literals
would require changing our parser front-end, which is precisely what I've
started doing, but couldn't get a chance to complete. These are not
low-hanging fruits. :)

**Comment by kyessenov** [comment]
In CEL, it's only error to reference undefined fields:
```If e is a message and f is declared, but the field is not set, the default value of the field's type will be produced. Note that this is null for messages or the according primitive default value as determined by proto2 or proto3 semantics.```
What changes between proto2 and proto3 for defined fields? Lack of presence checks and unusual defaulting?

**Comment by kyessenov** [comment]
@ozevren given that the total body of written Mixer expressions is only going to go up, doing a semantic change now is a lot easier. Do we really need `has()`? It's only useful for presence checks in proto2, and we rely exclusively on proto3 in our definitions.

**Comment by ozevren** [comment]
Yes, I agree doing a semantic change now is a lot easier. We should do
that. But doing these changes is A-Lot-Of-Work(TM), is breaking, and is not
something that can (or should) be sneaked in. In places where it is cheap
to do so (and non-breaking), we've already done some work. I am sure we can
do more. Happy to do that if it serves an immediate purpose. Otherwise,
IMO, it is better to approach this holistically, and be explicit about it.

**Comment by wora** [comment]
One key difference between proto2 and proto3 is proto3 doesn't have default
value or presence (except for message fields). Currently, Mixer attribute
behave like proto2, while CEL behaves like proto3. Both Envoy and Istio use
proto3 everywhere, so it is really hard and confusing to keep attributes as
proto2 semantics.

This is a massive refactoring work. In the long term, it is totally worth
doing, so we can use proto3 and gRPC everywhere, plus CEL and others. I
highly recommend we take the cost.

We can meet to discuss how to make it feasible.

**Comment by ozevren** [comment]
I think it is mostly a matter of timing, more than anything else.

**Comment by kyessenov** [comment]
Can you share pointers to CEL/mixer language engine?
I would like to see if I can contribute with lists/maps at least.

**Comment by wora** [comment]
https://github.com/google/cel-spec

I don't know where is the engine part.

**Comment by mandarjog** [comment]
We do not directly use `has()` in Mixer, but we have `firstNonEmpty`    --> ` a | b | c ` type expressions which serve a related purpose.

In a `google.protobuf.Struct` protos `has` is actually meaningful because CEL is supposed to automagically convert these structures.
Even if we have a fully schematized protocol, we will always have `Struct` as an extension mechanism, and then we do need test for presence.

**Comment by kyessenov** [comment]
What if we define `expr_a | expr_b` as `eval(expr_b)` if `eval(expr_a)`
reduces to an error instead of null?

**Comment by kyessenov** [comment]
Yeah, I see, disregard. It's a problem indeed with the Elvis operator.
